"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages

APP = ['devserver.py']
DATA_FILES = ['audioshoe/sample/test.mp3']
REQUIREMENTS = ['jinja2', 'requests', 'numpy', 'torch', 'torchaudio']

setup(
    name='greenland',
    version='0.0.3',
    app=APP,
    data_files=DATA_FILES,
    packages=find_packages(),
    install_requires=REQUIREMENTS,
    setup_requires=['py2app'],
)
