#!/usr/bin/python3

"""Enumeration types for linguistic models."""

import enum

class NounSubtype(enum.Enum):
    """Subtypes for nouns."""
    HUMAN = "human"
    ANIMAL = "animal"
    PLANT = "plant"
    BUILDING_STRUCTURE = "building_structure"
    SMALL_MOVABLE_OBJECT = "small_movable_object"
    NATURAL_FEATURE = "natural_feature"
    TOOL_MACHINE = "tool_machine"
    MATERIAL_SUBSTANCE = "material_substance"
    CONCEPT_IDEA = "concept_idea"
    EMOTION_FEELING = "emotion_feeling"
    PROCESS_EVENT = "process_event"
    TIME_PERIOD = "time_period"
    GROUP_PEOPLE = "group_people"
    GROUP_ANIMAL = "group_animal"
    COLLECTION_THINGS = "collection_things"
    PERSONAL_NAME = "personal_name"
    PLACE_NAME = "place_name"
    ORGANIZATION_NAME = "organization_name"
    OTHER = "other"

class VerbSubtype(enum.Enum):
    """Subtypes for verbs."""
    PHYSICAL_ACTION = "physical_action"
    CREATION_ACTION = "creation_action"
    DESTRUCTION_ACTION = "destruction_action"
    MENTAL_STATE = "mental_state"
    EMOTIONAL_STATE = "emotional_state"
    POSSESSION = "possession"
    DEVELOPMENT = "development"
    CHANGE = "change"
    SPEAKING = "speaking"
    WRITING = "writing"
    EXPRESSING = "expressing"
    DIRECTIONAL_MOVEMENT = "directional_movement"
    MANNER_MOVEMENT = "manner_movement"
    OTHER = "other"

class AdjectiveSubtype(enum.Enum):
    """Subtypes for adjectives."""
    SIZE = "size"
    COLOR = "color"
    SHAPE = "shape"
    TEXTURE = "texture"
    QUALITY = "quality"
    AESTHETIC = "aesthetic"
    IMPORTANCE = "importance"
    ORIGIN = "origin"
    PURPOSE = "purpose"
    MATERIAL = "material"
    DEFINITE_QUANTITY = "definite_quantity"
    INDEFINITE_QUANTITY = "indefinite_quantity"
    DURATION = "duration"
    FREQUENCY = "frequency"
    SEQUENCE = "sequence"
    OTHER = "other"

class AdverbSubtype(enum.Enum):
    """Subtypes for adverbs."""
    STYLE = "style"
    ATTITUDE = "attitude"
    SPECIFIC_TIME = "specific_time"
    RELATIVE_TIME = "relative_time"
    DURATION = "duration"
    DIRECTION = "direction"
    LOCATION = "location"
    DISTANCE = "distance"
    INTENSITY = "intensity"
    COMPLETENESS = "completeness"
    APPROXIMATION = "approximation"
    DEFINITE_FREQUENCY = "definite_frequency"
    INDEFINITE_FREQUENCY = "indefinite_frequency"
    OTHER = "other"