"""English stopwords organized by categories."""

from langtools.en.grammatical_words import (
    ENGLISH_GRAMMATICAL_CONTRACTIONS,
    ENGLISH_GRAMMATICAL_WORDS_BY_CATEGORY,
)

stopwords = ENGLISH_GRAMMATICAL_WORDS_BY_CATEGORY

CONTRACTIONS = ENGLISH_GRAMMATICAL_CONTRACTIONS

COMMON_VERBS = [
    "said",
    "came",
    "come",
    "get",
    "going",
    "got",
    "know",
    "look",
    "looked",
    "make",
    "put",
    "say",
    "see",
    "tell",
    "think",
    "thought",
    "took",
    "went",
    "asked",
    "began",
    "called",
    "felt",
    "found",
    "gave",
    "give",
    "heard",
    "let",
    "like",
    "liked",
    "made",
    "seemed",
    "took",
    "go",
    "take",
    "use",
    "want",
]
COMMON_NOUNS = [
    "way",
    "thing",
    "place",
    "room",
    "door",
    "face",
    "head",
    "house",
    "man",
    "men",
    "mind",
    "moment",
    "mother",
    "father",
    "people",
    "person",
    "life",
    "nothing",
    "something",
    "anything",
    "love",
    "world",
]
COMMON_ADVERBS = [
    "now",
    "then",
    "here",
    "there",
    "where",
    "when",
    "how",
    "why",
    "again",
    "ever",
    "far",
    "forward",
    "only",
    "quite",
    "still",
    "too",
    "very",
    "always",
    "never",
    "not",
    "once",
    "more",
    "most",
    "good",
    "well",
    "new",
    "used",
    "yet",
]
MISC_WORDS = [
    "yes",
    "no",
    "just",
    "right",
    "left",
    "same",
    "even",
    "down",
    "away",
    "back",
    "much",
    "whatever",
    "enough",
    "also",
    "else",
    "other",
    "one",
    "two",
    "three",
    "great",
    "many",
    "little",
    "time",
    "first",
    "second",
    "next",
    "last",
]

# Create a flat list of all stopwords for easier use
all_stopwords = []
for category in stopwords.values():
    all_stopwords.extend(category)

# Remove duplicates and sort
all_stopwords = sorted(list(set(all_stopwords)))
