import lib.exemplars.tasks.wars_of_roses_exemplar
import lib.exemplars.tasks.granite_definition_exemplar
import lib.exemplars.tasks.granite_structured_def_exemplar
import lib.exemplars.tasks.poetry_exemplar
import lib.exemplars.tasks.poker_scorer_exemplar
import lib.exemplars.tasks.firefighter_dialogue_exemplar
import lib.exemplars.tasks.zebra_puzzle_exemplar
import lib.exemplars.tasks.wordfreq_translation_exemplar