#!/usr/bin/python3

"""Routes for browsing, creating, and editing concepts.

Concepts are encyclopedia-style entries (e.g. "World War II", "Art Deco"). The
Create-Page form collects a title, a one-sentence description, and 2-10 source
URLs; the body is then generated by the Vovere agent from those sources. Bodies
may contain ``[[wiki links]]`` to other concepts.
"""

import json
import logging
from typing import TYPE_CHECKING, Any, Callable, Dict, List, cast
from urllib.parse import urlparse

import constants
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask.typing import ResponseReturnValue

from barsukas.helpers.wikilinks import get_resolved_link_targets, render_concept_body
from storage.backend.config import DataSourceConfig
from storage.concept_service import (
    create_concept_from_qid,
    demote_concept_to_sub,
    file_sub_concept_from_qid,
    promote_sub_concept,
)
from storage.crud.concept import (
    create_concept,
    create_sub_concept,
    delete_concept,
    delete_sub_concept,
    get_concept_by_slug,
    get_link_for_qid,
    get_qids_for_sub_concept,
    get_sub_concept_by_slug,
    link_lemma_to_concept,
    unlink_lemma_from_concept,
    update_concept,
    update_sub_concept,
)
from storage.models.schema import Lemma
from storage.models.concept import (
    MAX_CONCEPT_SOURCES,
    SUB_CONCEPT_CATEGORIES,
    ConceptWikidataIndex,
    normalize_concept_slug,
)
from storage.queries.concept import (
    count_concepts,
    count_sub_concepts,
    get_backlinks,
    list_concepts,
    list_sub_concepts,
)
from storage.wikidata import fetch_wikidata_concept_seed, normalize_qid

BLOCKED_SOURCE_HOSTS: frozenset[str] = frozenset({"wikidata.org", "www.wikidata.org"})

if TYPE_CHECKING:
    from barsukas.app import BarsukasFlask
    from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

bp = Blueprint("concepts", __name__, url_prefix="/concepts")


def _get_config() -> DataSourceConfig:
    """Return the Flask app's DataSourceConfig."""
    app: "BarsukasFlask" = current_app  # type: ignore[assignment]
    return app.backend_config


def _is_readonly() -> bool:
    """Return True if concept editing should be disabled."""
    if bool(current_app.config.get("CONCEPTS_WRITABLE", False)):
        return False
    return bool(current_app.config.get("READONLY", False))


def _concept_session() -> "Session":
    """Return the session that owns concept reads and writes."""
    return cast("Session", getattr(g, "concepts_db", g.db))


def _outbound_allowed() -> bool:
    """Return True if outbound LLM/source-fetch calls are permitted."""
    return bool(current_app.config.get("ALLOW_OUTBOUND_CALLS", True))


def _source_key(source: Dict[str, Any]) -> str:
    """Return a stable de-duplication key for a source dict."""
    return str(source.get("url", "")).strip().rstrip("/").casefold()


def _merge_sources(*source_lists: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Merge source lists by URL, preserving first occurrence order."""
    merged_sources: List[Dict[str, Any]] = []
    seen_sources: set[str] = set()
    for source_list in source_lists:
        for source in source_list:
            source_key = _source_key(source)
            if not source_key or source_key in seen_sources:
                continue
            merged_sources.append(source)
            seen_sources.add(source_key)
            if len(merged_sources) >= MAX_CONCEPT_SOURCES:
                return merged_sources
    return merged_sources


def _is_allowed_generation_source_url(url: str) -> bool:
    """Return False for source URLs that produce unusable generation text."""
    parsed_url = urlparse(url)
    host = parsed_url.netloc.casefold()
    return host not in BLOCKED_SOURCE_HOSTS


def _parse_sources_form(raw: str) -> List[Dict[str, Any]]:
    """Parse the sources textarea (one URL per line) into source dicts.

    Args:
        raw: Newline-separated URLs from the form.

    Returns:
        Up to MAX_CONCEPT_SOURCES ``{"url": ...}`` dicts (blank lines dropped).
    """
    sources: List[Dict[str, Any]] = []
    for line in raw.splitlines():
        url = line.strip()
        if url and _is_allowed_generation_source_url(url):
            sources.append({"url": url})
    return _merge_sources(sources)


def _concept_sources(concept: Any) -> List[Dict[str, Any]]:
    """Return parsed concept sources."""
    if not concept.sources:
        return []
    parsed_sources = json.loads(concept.sources)
    if isinstance(parsed_sources, list):
        return [source for source in parsed_sources if isinstance(source, dict)]
    return []


def _source_urls_text(sources: List[Dict[str, Any]]) -> str:
    """Render source URLs for the textarea editor."""
    return "\n".join(str(source.get("url", "")) for source in sources)


def _generate_body(title: str, summary: str, sources: List[Dict[str, Any]], model: str) -> str:
    """Generate a concept body via the Vovere agent.

    Imported lazily so the route module stays importable without LLM clients.
    """
    return _body_generator_for_model(model)(title, summary, sources)


def _body_generator_for_model(model: str) -> Callable[[str, str, List[Dict[str, Any]]], str]:
    """Return a (title, summary, sources) -> body callable backed by Vovere."""
    from agents.vovere import VovereAgent

    config = _get_config().with_model(model)
    agent = VovereAgent(config)

    def generate(title: str, summary: str, sources: List[Dict[str, Any]]) -> str:
        return agent.generate_body(title, summary, sources)

    return generate


CONCEPTS_PER_PAGE = 50


@bp.route("/")
def list_concepts_view() -> ResponseReturnValue:
    """List concepts with optional search, verified filter, and pagination."""
    search = request.args.get("q", "").strip()
    verified_only = request.args.get("verified") == "1"

    total = count_concepts(_concept_session(), search=search, verified_only=verified_only)
    total_pages = max(1, (total + CONCEPTS_PER_PAGE - 1) // CONCEPTS_PER_PAGE)

    try:
        page = int(request.args.get("page", "1"))
    except ValueError:
        page = 1
    page = max(1, min(page, total_pages))

    concepts = list_concepts(
        _concept_session(),
        search=search,
        verified_only=verified_only,
        limit=CONCEPTS_PER_PAGE,
        offset=(page - 1) * CONCEPTS_PER_PAGE,
    )
    return render_template(
        "concepts/list.html",
        concepts=concepts,
        total=total,
        search=search,
        verified_only=verified_only,
        readonly=_is_readonly(),
        page=page,
        total_pages=total_pages,
    )


@bp.route("/new")
def new_concept() -> ResponseReturnValue:
    """Render the Create-Page form."""
    if _is_readonly():
        flash("Cannot create concepts in read-only mode", "error")
        return redirect(url_for("concepts.list_concepts_view"))
    return render_template(
        "concepts/form.html",
        concept=None,
        default_model=constants.DEFAULT_MODEL,
        max_sources=MAX_CONCEPT_SOURCES,
        outbound_allowed=_outbound_allowed(),
    )


@bp.route("/wikidata-preview")
def wikidata_preview() -> ResponseReturnValue:
    """Return a small JSON preview for a complete Wikidata Q-id."""
    qid = normalize_qid(request.args.get("qid", ""))
    if qid is None:
        return jsonify({"found": False, "error": "invalid_qid"}), 400
    include_regional_wikis = request.args.get("include_regional_wikis") == "1"
    seed = fetch_wikidata_concept_seed(qid, include_regional_wikis=include_regional_wikis)
    if seed is None:
        return jsonify({"found": False, "qid": qid})
    return jsonify(
        {
            "found": True,
            "qid": seed.qid,
            "title": seed.title,
            "summary": seed.summary,
            "sources": seed.sources,
        }
    )


@bp.route("/create", methods=["POST"])
def create() -> ResponseReturnValue:
    """Create a concept, generating its body from the supplied sources."""
    if _is_readonly():
        flash("Cannot create concepts in read-only mode", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    wikidata_qid = normalize_qid(request.form.get("wikidata_qid", ""))
    title = request.form.get("title", "").strip()
    summary = request.form.get("summary", "").strip()
    sources = _parse_sources_form(request.form.get("sources", ""))
    model = request.form.get("model", "").strip() or constants.DEFAULT_MODEL
    include_regional_wikis = request.form.get("include_regional_wikis") == "1"

    # Q-id-seeded creation goes through the shared concept-creation service so
    # Barsukas and bulk agents (voverukas) use one implementation.
    if wikidata_qid is not None:
        body_generator = None
        if _outbound_allowed():
            body_generator = _body_generator_for_model(model)
        else:
            flash("Outbound calls are disabled; saved without a generated body.", "warning")

        result = create_concept_from_qid(
            _concept_session(),
            wikidata_qid,
            body_generator=body_generator,
            source_model=model if body_generator else None,
            include_regional_wikis=include_regional_wikis,
        )
        if result.status == "exists" and result.concept is not None:
            flash(
                f"Wikidata ID {wikidata_qid} is already linked to {result.concept.title!r}.",
                "error",
            )
            return redirect(url_for("concepts.detail", slug=result.concept.slug))
        if result.status == "unresolved":
            flash(f"Could not resolve Wikidata ID {wikidata_qid}.", "error")
            return redirect(url_for("concepts.new_concept"))
        if result.concept is None:
            flash("Failed to create the concept.", "error")
            return redirect(url_for("concepts.new_concept"))
        if result.detail.startswith("saved without body"):
            flash(f"Saved the page, but body generation failed: {result.detail}", "warning")
        flash(f"Created concept {result.concept.title!r}.", "success")
        return redirect(url_for("concepts.detail", slug=result.concept.slug))

    # Manual (no Q-id) creation: keep the inline path.
    flash(
        "Creating a concept without a Wikidata Q-id; please add one later if a good match exists.",
        "warning",
    )
    if not title:
        flash("A title or Wikidata Q-id is required.", "error")
        return redirect(url_for("concepts.new_concept"))
    if get_concept_by_slug(_concept_session(), title) is not None:
        flash(f"A concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.new_concept"))

    body = ""
    source_model = None
    if _outbound_allowed():
        try:
            body = _generate_body(title, summary, sources, model)
            source_model = model
        except Exception as exc:  # generation failure should not lose the entry
            logger.exception("Concept body generation failed")
            flash(f"Saved the page, but body generation failed: {exc}", "warning")
    else:
        flash("Outbound calls are disabled; saved without a generated body.", "warning")

    concept = create_concept(
        _concept_session(),
        title=title,
        summary=summary,
        body=body,
        sources=sources,
        source_model=source_model,
    )
    if concept is None:
        flash("Failed to create the concept.", "error")
        return redirect(url_for("concepts.new_concept"))

    flash(f"Created concept {concept.title!r}.", "success")
    return redirect(url_for("concepts.detail", slug=concept.slug))


@bp.route("/<path:slug>")
def detail(slug: str) -> ResponseReturnValue:
    """Show a single concept with its rendered body and backlinks."""
    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    resolved_targets = get_resolved_link_targets(_concept_session(), concept.body or "")
    rendered_body = render_concept_body(concept.body or "", resolved_targets)
    sources = _concept_sources(concept)
    backlinks = get_backlinks(_concept_session(), concept.slug)
    wikidata_links = (
        _concept_session()
        .query(ConceptWikidataIndex)
        .filter(ConceptWikidataIndex.concept_id == concept.id)
        .all()
    )

    # Lemma pairing. The concept's Q-id is what the link is keyed on; if the
    # concept has no Q-id it cannot be paired with a lemma (the release export
    # only carries the Q-id). The link itself lives in the lemma/main DB (g.db).
    concept_qid = wikidata_links[0].qid if wikidata_links else None
    paired_link = get_link_for_qid(g.db, concept_qid) if concept_qid else None
    paired_lemma = (
        g.db.query(Lemma).filter(Lemma.id == paired_link.lemma_id).first()
        if paired_link is not None
        else None
    )

    # Candidate lemmas for a lemma-search query (one-off, ordinary form submit).
    lemma_query = request.args.get("lemma_q", "").strip()
    lemma_candidates: List[Lemma] = []
    if concept_qid and paired_link is None and lemma_query:
        lemma_candidates = (
            g.db.query(Lemma)
            .filter(Lemma.lemma_text.ilike(f"%{lemma_query}%"))
            .order_by(Lemma.lemma_text, Lemma.id)
            .limit(25)
            .all()
        )

    return render_template(
        "concepts/detail.html",
        concept=concept,
        rendered_body=rendered_body,
        sources=sources,
        backlinks=backlinks,
        readonly=_is_readonly(),
        wikidata_links=wikidata_links,
        concept_qid=concept_qid,
        paired_link=paired_link,
        paired_lemma=paired_lemma,
        lemma_query=lemma_query,
        lemma_candidates=lemma_candidates,
        sub_categories=SUB_CONCEPT_CATEGORIES,
    )


@bp.route("/<path:slug>/edit")
def edit(slug: str) -> ResponseReturnValue:
    """Render the edit form for an existing concept."""
    if _is_readonly():
        flash("Cannot edit concepts in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    sources = _concept_sources(concept)
    return render_template(
        "concepts/form.html",
        concept=concept,
        sources_text=_source_urls_text(sources),
        default_model=constants.DEFAULT_MODEL,
        max_sources=MAX_CONCEPT_SOURCES,
        outbound_allowed=_outbound_allowed(),
    )


@bp.route("/<path:slug>/update", methods=["POST"])
def update(slug: str) -> ResponseReturnValue:
    """Apply edits to a concept (title, summary, body, sources, verified)."""
    if _is_readonly():
        flash("Cannot edit concepts in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    title = request.form.get("title", "").strip()
    if not title:
        flash("A title is required.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    # Guard against renaming onto another existing concept's slug.
    new_slug = normalize_concept_slug(title)
    if new_slug != concept.slug and get_concept_by_slug(_concept_session(), new_slug) is not None:
        flash(f"A concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    updated = update_concept(
        _concept_session(),
        concept,
        title=title,
        summary=request.form.get("summary", "").strip(),
        body=request.form.get("body", ""),
        sources=_parse_sources_form(request.form.get("sources", "")),
        verified=request.form.get("verified") == "1",
    )
    if updated is None:
        flash("Failed to update the concept.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    flash("Concept updated.", "success")
    return redirect(url_for("concepts.detail", slug=updated.slug))


@bp.route("/<path:slug>/link-lemma", methods=["POST"])
def link_lemma(slug: str) -> ResponseReturnValue:
    """Pair this concept with a lemma (by lemma id), keyed on the concept Q-id."""
    if _is_readonly():
        flash("Cannot link lemmas in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    # The pairing is keyed on the concept's Q-id, since that is what the release
    # export carries. A concept with no Q-id cannot be paired.
    qid_row = (
        _concept_session()
        .query(ConceptWikidataIndex)
        .filter(ConceptWikidataIndex.concept_id == concept.id)
        .first()
    )
    if qid_row is None:
        flash("This concept has no Wikidata Q-id, so it cannot be paired with a lemma.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    try:
        lemma_id = int(request.form.get("lemma_id", ""))
    except ValueError:
        flash("Invalid lemma selection.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    lemma = g.db.query(Lemma).filter(Lemma.id == lemma_id).first()
    if lemma is None:
        flash("That lemma no longer exists.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    link = link_lemma_to_concept(
        g.db, lemma_id, qid_row.qid, concept_slug=concept.slug, verified=True
    )
    if link is None:
        flash(
            "Could not pair: the lemma or this concept is already linked to something else.",
            "error",
        )
        return redirect(url_for("concepts.detail", slug=slug))

    flash(f"Paired with lemma {lemma.lemma_text!r}.", "success")
    return redirect(url_for("concepts.detail", slug=slug))


@bp.route("/<path:slug>/unlink-lemma", methods=["POST"])
def unlink_lemma(slug: str) -> ResponseReturnValue:
    """Remove the lemma pairing for this concept."""
    if _is_readonly():
        flash("Cannot unlink in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    try:
        lemma_id = int(request.form.get("lemma_id", ""))
    except ValueError:
        flash("Invalid lemma selection.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    if unlink_lemma_from_concept(g.db, lemma_id=lemma_id):
        flash("Removed the lemma pairing.", "success")
    else:
        flash("No pairing to remove.", "warning")
    return redirect(url_for("concepts.detail", slug=slug))


@bp.route("/<path:slug>/regenerate", methods=["GET", "POST"])
def regenerate(slug: str) -> ResponseReturnValue:
    """Review sources, then regenerate the body after explicit confirmation."""
    if _is_readonly():
        flash("Cannot regenerate in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))
    if not _outbound_allowed():
        flash("Outbound calls are disabled; cannot regenerate.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    sources = _concept_sources(concept)
    sources_text = _source_urls_text(sources)
    if request.method == "GET":
        return render_template(
            "concepts/regenerate.html",
            concept=concept,
            sources_text=sources_text,
            default_model=constants.DEFAULT_MODEL,
            max_sources=MAX_CONCEPT_SOURCES,
        )

    if request.form.get("confirm_regenerate") != "1":
        flash("Please confirm the LLM cost before regenerating.", "error")
        return render_template(
            "concepts/regenerate.html",
            concept=concept,
            sources_text=request.form.get("sources", sources_text),
            default_model=request.form.get("model", "").strip() or constants.DEFAULT_MODEL,
            max_sources=MAX_CONCEPT_SOURCES,
        )

    model = request.form.get("model", "").strip() or constants.DEFAULT_MODEL
    sources = _parse_sources_form(request.form.get("sources", ""))
    try:
        body = _generate_body(concept.title, concept.summary or "", sources, model)
    except Exception as exc:
        logger.exception("Concept body regeneration failed")
        flash(f"Regeneration failed: {exc}", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    update_concept(_concept_session(), concept, body=body, sources=sources, source_model=model)
    flash("Regenerated concept body.", "success")
    return redirect(url_for("concepts.detail", slug=concept.slug))


@bp.route("/<path:slug>/delete", methods=["POST"])
def delete(slug: str) -> ResponseReturnValue:
    """Delete a concept."""
    if _is_readonly():
        flash("Cannot delete in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    title = concept.title
    delete_concept(_concept_session(), concept)
    flash(f"Deleted concept {title!r}.", "success")
    return redirect(url_for("concepts.list_concepts_view"))


@bp.route("/<path:slug>/demote", methods=["POST"])
def demote(slug: str) -> ResponseReturnValue:
    """Demote a main concept to a sub-concept (discards body and sources)."""
    if _is_readonly():
        flash("Cannot demote in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    category = request.form.get("category", "")
    if category not in SUB_CONCEPT_CATEGORIES:
        flash("Pick a sub-concept category to demote into.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    sub_concept = demote_concept_to_sub(_concept_session(), concept, category)
    if sub_concept is None:
        flash("Could not demote: a sub-concept with this slug already exists.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    flash(f"Demoted {sub_concept.title!r} to the sub-encyclopedia.", "success")
    return redirect(url_for("concepts.sub_detail", slug=sub_concept.slug))


# --- Sub-encyclopedia ------------------------------------------------------------
#
# Sub-concepts (see storage.models.concept.SubConcept) are lightweight tracked
# topics kept out of the main encyclopedia. These routes are static-prefixed
# with /sub, which Werkzeug matches ahead of the /<path:slug> concept detail.

SUB_CONCEPTS_PER_PAGE = 100


@bp.route("/sub")
def sub_list() -> ResponseReturnValue:
    """List sub-concepts with optional search, category filter, and pagination."""
    search = request.args.get("q", "").strip()
    category = request.args.get("category", "").strip()
    if category not in SUB_CONCEPT_CATEGORIES:
        category = ""

    total = count_sub_concepts(_concept_session(), search=search, category=category or None)
    total_pages = max(1, (total + SUB_CONCEPTS_PER_PAGE - 1) // SUB_CONCEPTS_PER_PAGE)

    try:
        page = int(request.args.get("page", "1"))
    except ValueError:
        page = 1
    page = max(1, min(page, total_pages))

    sub_concepts = list_sub_concepts(
        _concept_session(),
        search=search,
        category=category or None,
        limit=SUB_CONCEPTS_PER_PAGE,
        offset=(page - 1) * SUB_CONCEPTS_PER_PAGE,
    )
    return render_template(
        "concepts/sub_list.html",
        sub_concepts=sub_concepts,
        total=total,
        search=search,
        category=category,
        categories=SUB_CONCEPT_CATEGORIES,
        readonly=_is_readonly(),
        page=page,
        total_pages=total_pages,
    )


@bp.route("/sub/new")
def sub_new() -> ResponseReturnValue:
    """Render the file-a-sub-concept form."""
    if _is_readonly():
        flash("Cannot create sub-concepts in read-only mode", "error")
        return redirect(url_for("concepts.sub_list"))
    return render_template(
        "concepts/sub_form.html",
        sub_concept=None,
        categories=SUB_CONCEPT_CATEGORIES,
    )


@bp.route("/sub/create", methods=["POST"])
def sub_create() -> ResponseReturnValue:
    """File a sub-concept from a Wikidata Q-id, or create one manually."""
    if _is_readonly():
        flash("Cannot create sub-concepts in read-only mode", "error")
        return redirect(url_for("concepts.sub_list"))

    category = request.form.get("category", "")
    if category not in SUB_CONCEPT_CATEGORIES:
        flash("A sub-concept category is required.", "error")
        return redirect(url_for("concepts.sub_new"))

    wikidata_qid = normalize_qid(request.form.get("wikidata_qid", ""))
    title = request.form.get("title", "").strip()
    summary = request.form.get("summary", "").strip()
    notes = request.form.get("notes", "").strip() or None

    # Q-id filing goes through the shared service so Barsukas and Voveraite use
    # one implementation (seed fetch, idempotency, index link -- no LLM).
    if wikidata_qid is not None:
        result = file_sub_concept_from_qid(_concept_session(), wikidata_qid, category, notes=notes)
        if result.status == "filed" and result.sub_concept is not None:
            if result.detail:
                flash(result.detail.capitalize() + ".", "warning")
            flash(f"Filed sub-concept {result.sub_concept.title!r}.", "success")
            return redirect(url_for("concepts.sub_detail", slug=result.sub_concept.slug))
        if result.status == "exists":
            flash(f"Wikidata ID {wikidata_qid}: {result.detail}.", "error")
            if result.sub_concept is not None:
                return redirect(url_for("concepts.sub_detail", slug=result.sub_concept.slug))
            return redirect(url_for("concepts.sub_new"))
        flash(f"Could not file {wikidata_qid}: {result.detail or result.status}.", "error")
        return redirect(url_for("concepts.sub_new"))

    if not title:
        flash("A title or Wikidata Q-id is required.", "error")
        return redirect(url_for("concepts.sub_new"))
    sub_concept = create_sub_concept(
        _concept_session(),
        title=title,
        category=category,
        summary=summary or None,
        notes=notes,
    )
    if sub_concept is None:
        flash(f"A sub-concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.sub_new"))

    flash(f"Created sub-concept {sub_concept.title!r}.", "success")
    return redirect(url_for("concepts.sub_detail", slug=sub_concept.slug))


@bp.route("/sub/<path:slug>")
def sub_detail(slug: str) -> ResponseReturnValue:
    """Show a single sub-concept with its Q-ids and backlinks."""
    sub_concept = get_sub_concept_by_slug(_concept_session(), slug)
    if sub_concept is None:
        flash(f"No sub-concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.sub_list"))

    qids = get_qids_for_sub_concept(_concept_session(), sub_concept.id)
    backlinks = get_backlinks(_concept_session(), sub_concept.slug, qids=qids)
    shadowing_concept = get_concept_by_slug(_concept_session(), sub_concept.slug)

    return render_template(
        "concepts/sub_detail.html",
        sub_concept=sub_concept,
        qids=qids,
        backlinks=backlinks,
        shadowing_concept=shadowing_concept,
        readonly=_is_readonly(),
    )


@bp.route("/sub/<path:slug>/edit")
def sub_edit(slug: str) -> ResponseReturnValue:
    """Render the edit form for an existing sub-concept."""
    if _is_readonly():
        flash("Cannot edit sub-concepts in read-only mode", "error")
        return redirect(url_for("concepts.sub_detail", slug=slug))

    sub_concept = get_sub_concept_by_slug(_concept_session(), slug)
    if sub_concept is None:
        flash(f"No sub-concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.sub_list"))

    return render_template(
        "concepts/sub_form.html",
        sub_concept=sub_concept,
        categories=SUB_CONCEPT_CATEGORIES,
    )


@bp.route("/sub/<path:slug>/update", methods=["POST"])
def sub_update(slug: str) -> ResponseReturnValue:
    """Apply edits to a sub-concept (title, category, summary, verified, notes)."""
    if _is_readonly():
        flash("Cannot edit sub-concepts in read-only mode", "error")
        return redirect(url_for("concepts.sub_detail", slug=slug))

    sub_concept = get_sub_concept_by_slug(_concept_session(), slug)
    if sub_concept is None:
        flash(f"No sub-concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.sub_list"))

    title = request.form.get("title", "").strip()
    if not title:
        flash("A title is required.", "error")
        return redirect(url_for("concepts.sub_edit", slug=slug))
    category = request.form.get("category", "")
    if category not in SUB_CONCEPT_CATEGORIES:
        flash("A sub-concept category is required.", "error")
        return redirect(url_for("concepts.sub_edit", slug=slug))

    new_slug = normalize_concept_slug(title)
    if (
        new_slug != sub_concept.slug
        and get_sub_concept_by_slug(_concept_session(), new_slug) is not None
    ):
        flash(f"A sub-concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.sub_edit", slug=slug))

    updated = update_sub_concept(
        _concept_session(),
        sub_concept,
        title=title,
        category=category,
        summary=request.form.get("summary", "").strip(),
        verified=request.form.get("verified") == "1",
        notes=request.form.get("notes", "").strip(),
    )
    if updated is None:
        flash("Failed to update the sub-concept.", "error")
        return redirect(url_for("concepts.sub_edit", slug=slug))

    flash("Sub-concept updated.", "success")
    return redirect(url_for("concepts.sub_detail", slug=updated.slug))


@bp.route("/sub/<path:slug>/delete", methods=["POST"])
def sub_delete(slug: str) -> ResponseReturnValue:
    """Delete a sub-concept (its Q-ids revert to untriaged)."""
    if _is_readonly():
        flash("Cannot delete in read-only mode", "error")
        return redirect(url_for("concepts.sub_detail", slug=slug))

    sub_concept = get_sub_concept_by_slug(_concept_session(), slug)
    if sub_concept is None:
        flash(f"No sub-concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.sub_list"))

    title = sub_concept.title
    delete_sub_concept(_concept_session(), sub_concept)
    flash(f"Deleted sub-concept {title!r}.", "success")
    return redirect(url_for("concepts.sub_list"))


@bp.route("/sub/<path:slug>/promote", methods=["POST"])
def sub_promote(slug: str) -> ResponseReturnValue:
    """Promote a sub-concept to a main concept (no body yet; generate later)."""
    if _is_readonly():
        flash("Cannot promote in read-only mode", "error")
        return redirect(url_for("concepts.sub_detail", slug=slug))

    sub_concept = get_sub_concept_by_slug(_concept_session(), slug)
    if sub_concept is None:
        flash(f"No sub-concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.sub_list"))

    concept = promote_sub_concept(_concept_session(), sub_concept)
    if concept is None:
        flash("Could not promote: a main concept with this slug already exists.", "error")
        return redirect(url_for("concepts.sub_detail", slug=slug))

    flash(f"Promoted {concept.title!r} to a main concept.", "success")
    return redirect(url_for("concepts.detail", slug=concept.slug))
