#!/usr/bin/python3

"""Routes for browsing, creating, and editing concepts.

Concepts are encyclopedia-style entries (e.g. "World War II", "Art Deco"). The
Create-Page form collects a title, a one-sentence description, and 2-10 source
URLs; the body is then generated by the Vovere agent from those sources. Bodies
may contain ``[[wiki links]]`` to other concepts.
"""

import json
import logging
from typing import TYPE_CHECKING, Any, Dict, List, cast

import constants
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask.typing import ResponseReturnValue

from barsukas.helpers.wikilinks import get_existing_link_targets, render_concept_body
from storage.backend.config import DataSourceConfig
from storage.crud.concept import (
    create_concept,
    delete_concept,
    get_concept_by_slug,
    get_wikidata_index,
    link_wikidata_concept,
    update_concept,
)
from storage.models.concept import (
    MAX_CONCEPT_SOURCES,
    ConceptWikidataIndex,
    normalize_concept_slug,
)
from storage.queries.concept import count_concepts, get_backlinks, list_concepts
from storage.wikidata import fetch_wikidata_concept_seed, normalize_qid

if TYPE_CHECKING:
    from barsukas.app import BarsukasFlask
    from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

bp = Blueprint("concepts", __name__, url_prefix="/concepts")


def _get_config() -> DataSourceConfig:
    """Return the Flask app's DataSourceConfig."""
    app: "BarsukasFlask" = current_app  # type: ignore[assignment]
    return app.backend_config


def _is_readonly() -> bool:
    """Return True if concept editing should be disabled."""
    if bool(current_app.config.get("CONCEPTS_WRITABLE", False)):
        return False
    return bool(current_app.config.get("READONLY", False))


def _concept_session() -> "Session":
    """Return the session that owns concept reads and writes."""
    return cast("Session", getattr(g, "concepts_db", g.db))


def _outbound_allowed() -> bool:
    """Return True if outbound LLM/source-fetch calls are permitted."""
    return bool(current_app.config.get("ALLOW_OUTBOUND_CALLS", True))


def _source_key(source: Dict[str, Any]) -> str:
    """Return a stable de-duplication key for a source dict."""
    return str(source.get("url", "")).strip().rstrip("/").casefold()


def _merge_sources(*source_lists: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Merge source lists by URL, preserving first occurrence order."""
    merged_sources: List[Dict[str, Any]] = []
    seen_sources: set[str] = set()
    for source_list in source_lists:
        for source in source_list:
            source_key = _source_key(source)
            if not source_key or source_key in seen_sources:
                continue
            merged_sources.append(source)
            seen_sources.add(source_key)
            if len(merged_sources) >= MAX_CONCEPT_SOURCES:
                return merged_sources
    return merged_sources


def _parse_sources_form(raw: str) -> List[Dict[str, Any]]:
    """Parse the sources textarea (one URL per line) into source dicts.

    Args:
        raw: Newline-separated URLs from the form.

    Returns:
        Up to MAX_CONCEPT_SOURCES ``{"url": ...}`` dicts (blank lines dropped).
    """
    sources: List[Dict[str, Any]] = []
    for line in raw.splitlines():
        url = line.strip()
        if url:
            sources.append({"url": url})
    return _merge_sources(sources)


def _concept_sources(concept: Any) -> List[Dict[str, Any]]:
    """Return parsed concept sources."""
    if not concept.sources:
        return []
    parsed_sources = json.loads(concept.sources)
    if isinstance(parsed_sources, list):
        return [source for source in parsed_sources if isinstance(source, dict)]
    return []


def _source_urls_text(sources: List[Dict[str, Any]]) -> str:
    """Render source URLs for the textarea editor."""
    return "\n".join(str(source.get("url", "")) for source in sources)


def _generate_body(title: str, summary: str, sources: List[Dict[str, Any]], model: str) -> str:
    """Generate a concept body via the Vovere agent.

    Imported lazily so the route module stays importable without LLM clients.
    """
    from agents.vovere import VovereAgent

    config = _get_config().with_model(model)
    agent = VovereAgent(config)
    return agent.generate_body(title, summary, sources)


@bp.route("/")
def list_concepts_view() -> ResponseReturnValue:
    """List concepts with optional search and verified filter."""
    search = request.args.get("q", "").strip()
    verified_only = request.args.get("verified") == "1"
    concepts = list_concepts(_concept_session(), search=search, verified_only=verified_only)
    return render_template(
        "concepts/list.html",
        concepts=concepts,
        total=count_concepts(_concept_session()),
        search=search,
        verified_only=verified_only,
        readonly=_is_readonly(),
    )


@bp.route("/new")
def new_concept() -> ResponseReturnValue:
    """Render the Create-Page form."""
    if _is_readonly():
        flash("Cannot create concepts in read-only mode", "error")
        return redirect(url_for("concepts.list_concepts_view"))
    return render_template(
        "concepts/form.html",
        concept=None,
        default_model=constants.DEFAULT_MODEL,
        max_sources=MAX_CONCEPT_SOURCES,
        outbound_allowed=_outbound_allowed(),
    )


@bp.route("/wikidata-preview")
def wikidata_preview() -> ResponseReturnValue:
    """Return a small JSON preview for a complete Wikidata Q-id."""
    qid = normalize_qid(request.args.get("qid", ""))
    if qid is None:
        return jsonify({"found": False, "error": "invalid_qid"}), 400
    include_regional_wikis = request.args.get("include_regional_wikis") == "1"
    seed = fetch_wikidata_concept_seed(qid, include_regional_wikis=include_regional_wikis)
    if seed is None:
        return jsonify({"found": False, "qid": qid})
    return jsonify(
        {
            "found": True,
            "qid": seed.qid,
            "title": seed.title,
            "summary": seed.summary,
            "sources": seed.sources,
        }
    )


@bp.route("/create", methods=["POST"])
def create() -> ResponseReturnValue:
    """Create a concept, generating its body from the supplied sources."""
    if _is_readonly():
        flash("Cannot create concepts in read-only mode", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    wikidata_qid = normalize_qid(request.form.get("wikidata_qid", ""))
    title = request.form.get("title", "").strip()
    summary = request.form.get("summary", "").strip()
    sources = _parse_sources_form(request.form.get("sources", ""))
    model = request.form.get("model", "").strip() or constants.DEFAULT_MODEL

    if wikidata_qid is None:
        flash(
            "Creating a concept without a Wikidata Q-id; please add one later if a good match exists.",
            "warning",
        )
    else:
        existing_index = get_wikidata_index(_concept_session(), wikidata_qid)
        if existing_index is not None and existing_index.concept is not None:
            flash(
                f"Wikidata ID {wikidata_qid} is already linked to {existing_index.concept.title!r}.",
                "error",
            )
            return redirect(url_for("concepts.detail", slug=existing_index.concept.slug))
        include_regional_wikis = request.form.get("include_regional_wikis") == "1"
        seed = fetch_wikidata_concept_seed(
            wikidata_qid, include_regional_wikis=include_regional_wikis
        )
        if seed is None:
            flash(f"Could not resolve Wikidata ID {wikidata_qid}.", "error")
            return redirect(url_for("concepts.new_concept"))
        title = title or seed.title
        summary = summary or seed.summary
        sources = _merge_sources(sources, seed.sources)

    if not title:
        flash("A title or Wikidata Q-id is required.", "error")
        return redirect(url_for("concepts.new_concept"))

    if get_concept_by_slug(_concept_session(), title) is not None:
        flash(f"A concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.new_concept"))

    body = ""
    source_model = None
    if _outbound_allowed():
        try:
            body = _generate_body(title, summary, sources, model)
            source_model = model
        except Exception as exc:  # generation failure should not lose the entry
            logger.exception("Concept body generation failed")
            flash(f"Saved the page, but body generation failed: {exc}", "warning")
    else:
        flash("Outbound calls are disabled; saved without a generated body.", "warning")

    concept = create_concept(
        _concept_session(),
        title=title,
        summary=summary,
        body=body,
        sources=sources,
        source_model=source_model,
    )
    if concept is None:
        flash("Failed to create the concept.", "error")
        return redirect(url_for("concepts.new_concept"))

    if wikidata_qid is not None:
        link_wikidata_concept(_concept_session(), wikidata_qid, concept)

    flash(f"Created concept {concept.title!r}.", "success")
    return redirect(url_for("concepts.detail", slug=concept.slug))


@bp.route("/<path:slug>")
def detail(slug: str) -> ResponseReturnValue:
    """Show a single concept with its rendered body and backlinks."""
    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    existing = get_existing_link_targets(_concept_session(), concept.body or "")
    rendered_body = render_concept_body(concept.body or "", existing)
    sources = _concept_sources(concept)
    backlinks = get_backlinks(_concept_session(), concept.slug)
    wikidata_links = (
        _concept_session()
        .query(ConceptWikidataIndex)
        .filter(ConceptWikidataIndex.concept_id == concept.id)
        .all()
    )

    return render_template(
        "concepts/detail.html",
        concept=concept,
        rendered_body=rendered_body,
        sources=sources,
        backlinks=backlinks,
        readonly=_is_readonly(),
        wikidata_links=wikidata_links,
    )


@bp.route("/<path:slug>/edit")
def edit(slug: str) -> ResponseReturnValue:
    """Render the edit form for an existing concept."""
    if _is_readonly():
        flash("Cannot edit concepts in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    sources = _concept_sources(concept)
    return render_template(
        "concepts/form.html",
        concept=concept,
        sources_text=_source_urls_text(sources),
        default_model=constants.DEFAULT_MODEL,
        max_sources=MAX_CONCEPT_SOURCES,
        outbound_allowed=_outbound_allowed(),
    )


@bp.route("/<path:slug>/update", methods=["POST"])
def update(slug: str) -> ResponseReturnValue:
    """Apply edits to a concept (title, summary, body, sources, verified)."""
    if _is_readonly():
        flash("Cannot edit concepts in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    title = request.form.get("title", "").strip()
    if not title:
        flash("A title is required.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    # Guard against renaming onto another existing concept's slug.
    new_slug = normalize_concept_slug(title)
    if new_slug != concept.slug and get_concept_by_slug(_concept_session(), new_slug) is not None:
        flash(f"A concept titled {title!r} already exists.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    updated = update_concept(
        _concept_session(),
        concept,
        title=title,
        summary=request.form.get("summary", "").strip(),
        body=request.form.get("body", ""),
        sources=_parse_sources_form(request.form.get("sources", "")),
        verified=request.form.get("verified") == "1",
    )
    if updated is None:
        flash("Failed to update the concept.", "error")
        return redirect(url_for("concepts.edit", slug=slug))

    flash("Concept updated.", "success")
    return redirect(url_for("concepts.detail", slug=updated.slug))


@bp.route("/<path:slug>/regenerate", methods=["GET", "POST"])
def regenerate(slug: str) -> ResponseReturnValue:
    """Review sources, then regenerate the body after explicit confirmation."""
    if _is_readonly():
        flash("Cannot regenerate in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))
    if not _outbound_allowed():
        flash("Outbound calls are disabled; cannot regenerate.", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    sources = _concept_sources(concept)
    sources_text = _source_urls_text(sources)
    if request.method == "GET":
        return render_template(
            "concepts/regenerate.html",
            concept=concept,
            sources_text=sources_text,
            default_model=constants.DEFAULT_MODEL,
            max_sources=MAX_CONCEPT_SOURCES,
        )

    if request.form.get("confirm_regenerate") != "1":
        flash("Please confirm the LLM cost before regenerating.", "error")
        return render_template(
            "concepts/regenerate.html",
            concept=concept,
            sources_text=request.form.get("sources", sources_text),
            default_model=request.form.get("model", "").strip() or constants.DEFAULT_MODEL,
            max_sources=MAX_CONCEPT_SOURCES,
        )

    model = request.form.get("model", "").strip() or constants.DEFAULT_MODEL
    sources = _parse_sources_form(request.form.get("sources", ""))
    try:
        body = _generate_body(concept.title, concept.summary or "", sources, model)
    except Exception as exc:
        logger.exception("Concept body regeneration failed")
        flash(f"Regeneration failed: {exc}", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    update_concept(_concept_session(), concept, body=body, sources=sources, source_model=model)
    flash("Regenerated concept body.", "success")
    return redirect(url_for("concepts.detail", slug=concept.slug))


@bp.route("/<path:slug>/delete", methods=["POST"])
def delete(slug: str) -> ResponseReturnValue:
    """Delete a concept."""
    if _is_readonly():
        flash("Cannot delete in read-only mode", "error")
        return redirect(url_for("concepts.detail", slug=slug))

    concept = get_concept_by_slug(_concept_session(), slug)
    if concept is None:
        flash(f"No concept found for {slug!r}.", "error")
        return redirect(url_for("concepts.list_concepts_view"))

    title = concept.title
    delete_concept(_concept_session(), concept)
    flash(f"Deleted concept {title!r}.", "success")
    return redirect(url_for("concepts.list_concepts_view"))
