#!/usr/bin/python3

"""Routes for the story library ("texts"): browsing, creating, and editing
text works and their versions.

A text work is the story/conversation/song/poem itself, as opposed to the
encyclopedia entry about it (see docs/fables_design.md). Authored works
(fables, folk tales, conversations, ...) get their texts generated by the
Ožys agent; canonical works (poems, songs, ...) get their single authoritative
text pasted in with a source and a required license.
"""

import logging
from typing import TYPE_CHECKING, Optional, cast

import constants
from flask import (
    Blueprint,
    current_app,
    flash,
    g,
    redirect,
    render_template,
    request,
    url_for,
)
from flask.typing import ResponseReturnValue

from barsukas.helpers.wikilinks import render_text_body
from storage.backend.config import DataSourceConfig
from storage.crud.concept import get_wikidata_index
from storage.crud.text_work import (
    create_text_version,
    create_text_work,
    delete_text_version,
    delete_text_work,
    get_text_version_by_id,
    get_text_version_for_slot,
    get_text_work_by_slug,
    update_text_version,
    update_text_work,
)
from storage.models.concept import normalize_concept_slug
from storage.models.text_work import (
    ALL_TEXT_TYPES,
    TEXT_TYPE_GROUPS,
    TextVersion,
    TextWork,
    is_intake_deferred_text_type,
)
from storage.queries.text_work import count_text_works, list_text_works
from storage.text_work_service import create_text_work_from_qid
from storage.wikidata import normalize_qid

if TYPE_CHECKING:
    from barsukas.app import BarsukasFlask
    from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

bp = Blueprint("texts", __name__, url_prefix="/texts")

TEXTS_PER_PAGE = 50

# License choices for canonical texts (free-form "Other" goes in text notes).
CANONICAL_LICENSE_CHOICES: tuple[str, ...] = (
    "public-domain",
    "CC0",
    "CC-BY",
    "CC-BY-SA",
    "developer-authored",
)


def _get_config() -> DataSourceConfig:
    """Return the Flask app's DataSourceConfig."""
    app: "BarsukasFlask" = current_app  # type: ignore[assignment]
    return app.backend_config


def _is_readonly() -> bool:
    """Return True if text editing should be disabled."""
    if bool(current_app.config.get("CONCEPTS_WRITABLE", False)):
        return False
    return bool(current_app.config.get("READONLY", False))


def _texts_session() -> "Session":
    """Return the session that owns text-work reads and writes.

    Text works live in the concepts database/backend (same posture as
    concepts: outside the lemma machinery).
    """
    return cast("Session", getattr(g, "concepts_db", g.db))


def _outbound_allowed() -> bool:
    """Return True if outbound LLM calls are permitted."""
    return bool(current_app.config.get("ALLOW_OUTBOUND_CALLS", True))


def _selectable_text_types() -> list[str]:
    """Text types accepted at intake (deferred types like 'quote' excluded)."""
    return [t for t in ALL_TEXT_TYPES if not is_intake_deferred_text_type(t)]


def _resolve_encyclopedia_target(qid: Optional[str]) -> Optional[dict]:
    """Resolve a Q-id through the shared index to its encyclopedia page.

    Returns a small dict for the template ({"kind", "slug", "title", "qid"}),
    or None when the Q-id is absent or has no concept/sub-concept yet.
    """
    if not qid:
        return None
    row = get_wikidata_index(_texts_session(), qid)
    if row is None:
        return None
    if row.concept is not None:
        return {"kind": "concept", "slug": row.concept.slug, "title": row.concept.title, "qid": qid}
    if row.sub_concept is not None:
        return {
            "kind": "sub_concept",
            "slug": row.sub_concept.slug,
            "title": row.sub_concept.title,
            "qid": qid,
        }
    return None


def _parse_difficulty(raw: str) -> Optional[int]:
    """Parse an optional difficulty form field ("" -> None)."""
    raw = raw.strip()
    if not raw:
        return None
    return int(raw)


@bp.route("/")
def list_texts_view() -> ResponseReturnValue:
    """List text works with optional search, type filter, and pagination."""
    search = request.args.get("q", "").strip()
    text_type = request.args.get("type", "").strip()
    if text_type not in ALL_TEXT_TYPES:
        text_type = ""

    total = count_text_works(_texts_session(), search=search, text_type=text_type or None)
    total_pages = max(1, (total + TEXTS_PER_PAGE - 1) // TEXTS_PER_PAGE)

    try:
        page = int(request.args.get("page", "1"))
    except ValueError:
        page = 1
    page = max(1, min(page, total_pages))

    works = list_text_works(
        _texts_session(),
        search=search,
        text_type=text_type or None,
        limit=TEXTS_PER_PAGE,
        offset=(page - 1) * TEXTS_PER_PAGE,
    )
    return render_template(
        "texts/list.html",
        works=works,
        total=total,
        search=search,
        text_type=text_type,
        type_groups=TEXT_TYPE_GROUPS,
        readonly=_is_readonly(),
        page=page,
        total_pages=total_pages,
    )


@bp.route("/new")
def new_work() -> ResponseReturnValue:
    """Render the add-a-work form."""
    if _is_readonly():
        flash("Cannot create texts in read-only mode", "error")
        return redirect(url_for("texts.list_texts_view"))
    return render_template(
        "texts/form.html",
        work=None,
        type_groups=TEXT_TYPE_GROUPS,
        selectable_types=_selectable_text_types(),
    )


@bp.route("/create", methods=["POST"])
def create() -> ResponseReturnValue:
    """Create a text work from a Wikidata Q-id, or manually by title."""
    if _is_readonly():
        flash("Cannot create texts in read-only mode", "error")
        return redirect(url_for("texts.list_texts_view"))

    text_type = request.form.get("text_type", "")
    if text_type not in _selectable_text_types():
        flash("A text type is required.", "error")
        return redirect(url_for("texts.new_work"))

    wikidata_qid = normalize_qid(request.form.get("wikidata_qid", ""))
    title = request.form.get("title", "").strip()
    attribution = request.form.get("attribution", "").strip() or None
    attribution_qid_raw = request.form.get("attribution_qid", "").strip()
    attribution_qid: Optional[str] = None
    if attribution_qid_raw:
        attribution_qid = normalize_qid(attribution_qid_raw)
        if attribution_qid is None:
            flash(f"Invalid attribution Q-id {attribution_qid_raw!r}.", "error")
            return redirect(url_for("texts.new_work"))
    summary = request.form.get("summary", "").strip()
    notes = request.form.get("notes", "").strip() or None

    # Q-id-seeded creation goes through the shared service (seed fetch,
    # idempotency), mirroring the concepts create flow.
    if wikidata_qid is not None:
        result = create_text_work_from_qid(
            _texts_session(),
            wikidata_qid,
            text_type,
            attribution_qid=attribution_qid,
            attribution=attribution,
            notes=notes,
        )
        if result.status == "exists":
            flash(f"Wikidata ID {wikidata_qid}: {result.detail}.", "error")
            if result.work is not None:
                return redirect(url_for("texts.detail", slug=result.work.slug))
            return redirect(url_for("texts.new_work"))
        if result.work is None:
            flash(f"Could not create the work: {result.detail or result.status}.", "error")
            return redirect(url_for("texts.new_work"))
        flash(f"Added {result.work.title!r} to the library.", "success")
        return redirect(url_for("texts.detail", slug=result.work.slug))

    # Manual creation (the only route for conversations, which have no Q-id).
    if not title:
        flash("A title or Wikidata Q-id is required.", "error")
        return redirect(url_for("texts.new_work"))
    if get_text_work_by_slug(_texts_session(), title) is not None:
        flash(f"A work titled {title!r} already exists.", "error")
        return redirect(url_for("texts.new_work"))

    work = create_text_work(
        _texts_session(),
        title=title,
        text_type=text_type,
        attribution_qid=attribution_qid,
        attribution=attribution,
        summary=summary or None,
        notes=notes,
    )
    if work is None:
        flash("Failed to create the work.", "error")
        return redirect(url_for("texts.new_work"))

    flash(f"Added {work.title!r} to the library.", "success")
    return redirect(url_for("texts.detail", slug=work.slug))


@bp.route("/<path:slug>")
def detail(slug: str) -> ResponseReturnValue:
    """Show a work with its rendered versions and encyclopedia cross-links."""
    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))

    rendered_versions = [
        (version, render_text_body(version.body or "")) for version in work.versions
    ]
    return render_template(
        "texts/detail.html",
        work=work,
        rendered_versions=rendered_versions,
        work_page=_resolve_encyclopedia_target(work.qid),
        attribution_page=_resolve_encyclopedia_target(work.attribution_qid),
        license_choices=CANONICAL_LICENSE_CHOICES,
        default_model=constants.DEFAULT_MODEL,
        readonly=_is_readonly(),
        outbound_allowed=_outbound_allowed(),
    )


@bp.route("/<path:slug>/edit")
def edit(slug: str) -> ResponseReturnValue:
    """Render the edit form for an existing work."""
    if _is_readonly():
        flash("Cannot edit texts in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))

    return render_template(
        "texts/form.html",
        work=work,
        type_groups=TEXT_TYPE_GROUPS,
        selectable_types=_selectable_text_types(),
    )


@bp.route("/<path:slug>/update", methods=["POST"])
def update(slug: str) -> ResponseReturnValue:
    """Apply edits to a work (title, type, Q-ids, attribution, summary, notes)."""
    if _is_readonly():
        flash("Cannot edit texts in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))

    title = request.form.get("title", "").strip()
    if not title:
        flash("A title is required.", "error")
        return redirect(url_for("texts.edit", slug=slug))
    text_type = request.form.get("text_type", "")
    if text_type not in _selectable_text_types():
        flash("A text type is required.", "error")
        return redirect(url_for("texts.edit", slug=slug))

    new_slug = normalize_concept_slug(title)
    if new_slug != work.slug and get_text_work_by_slug(_texts_session(), new_slug) is not None:
        flash(f"A work titled {title!r} already exists.", "error")
        return redirect(url_for("texts.edit", slug=slug))

    updated = update_text_work(
        _texts_session(),
        work,
        title=title,
        text_type=text_type,
        qid=request.form.get("wikidata_qid", "").strip() or None,
        attribution_qid=request.form.get("attribution_qid", "").strip() or None,
        attribution=request.form.get("attribution", "").strip(),
        summary=request.form.get("summary", "").strip(),
        verified=request.form.get("verified") == "1",
        notes=request.form.get("notes", "").strip(),
    )
    if updated is None:
        flash(
            "Failed to update the work (invalid Q-id, duplicate Q-id, or a "
            "canonical version pinning the type).",
            "error",
        )
        return redirect(url_for("texts.edit", slug=slug))

    flash("Work updated.", "success")
    return redirect(url_for("texts.detail", slug=updated.slug))


@bp.route("/<path:slug>/delete", methods=["POST"])
def delete(slug: str) -> ResponseReturnValue:
    """Delete a work and all its versions."""
    if _is_readonly():
        flash("Cannot delete in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))

    title = work.title
    delete_text_work(_texts_session(), work)
    flash(f"Deleted {title!r} and its versions.", "success")
    return redirect(url_for("texts.list_texts_view"))


@bp.route("/<path:slug>/generate", methods=["POST"])
def generate(slug: str) -> ResponseReturnValue:
    """Generate (or regenerate) a telling for an authored work via Ožys."""
    if _is_readonly():
        flash("Cannot generate in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))
    if not _outbound_allowed():
        flash("Outbound calls are disabled; cannot generate.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))
    if not work.is_authored:
        flash("Canonical works are transcribed, not generated.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    model = request.form.get("model", "").strip() or constants.DEFAULT_MODEL
    try:
        difficulty_level = _parse_difficulty(request.form.get("difficulty", ""))
    except ValueError:
        flash("Difficulty must be a whole number (or blank).", "error")
        return redirect(url_for("texts.detail", slug=slug))

    existing = get_text_version_for_slot(_texts_session(), work, "en", difficulty_level)
    if existing is not None and existing.verified:
        flash("That version is verified; un-verify it before regenerating.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    # Imported lazily so the route module stays importable without LLM clients.
    from agents.ozys import OzysAgent

    try:
        agent = OzysAgent(_get_config(), model=model)
        body = agent.generate_for_work(work, difficulty_level=difficulty_level)
    except Exception as exc:
        logger.exception("Text generation failed for %r", work.slug)
        flash(f"Generation failed: {exc}", "error")
        return redirect(url_for("texts.detail", slug=slug))

    if existing is not None:
        version = update_text_version(
            _texts_session(), existing, body=body, source_model=model, verified=False
        )
    else:
        version = create_text_version(
            _texts_session(),
            work,
            lang="en",
            body=body,
            difficulty_level=difficulty_level,
            source_model=model,
        )
    if version is None:
        flash("Generated a text but failed to store it.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    flash(f"Generated the {version.variant_label} version.", "success")
    return redirect(url_for("texts.detail", slug=slug))


@bp.route("/<path:slug>/versions/add", methods=["POST"])
def add_canonical_version(slug: str) -> ResponseReturnValue:
    """Add the canonical text of a canonical-type work (paste + license)."""
    if _is_readonly():
        flash("Cannot add texts in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        flash(f"No text work found for {slug!r}.", "error")
        return redirect(url_for("texts.list_texts_view"))
    if work.is_authored:
        flash("Authored works get their texts generated, not pasted.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    body = request.form.get("body", "").strip()
    text_source = request.form.get("text_source", "").strip()
    license = request.form.get("license", "").strip()
    if license not in CANONICAL_LICENSE_CHOICES:
        flash("A license is required for a canonical text.", "error")
        return redirect(url_for("texts.detail", slug=slug))

    version = create_text_version(
        _texts_session(),
        work,
        lang="en",
        body=body or None,
        is_canonical=True,
        text_source=text_source or None,
        license=license,
    )
    if version is None:
        flash("Could not add the canonical text (one may already exist).", "error")
        return redirect(url_for("texts.detail", slug=slug))

    flash("Added the canonical text.", "success")
    return redirect(url_for("texts.detail", slug=slug))


def _get_version_for_work(
    slug: str, version_id: int
) -> tuple[Optional[TextWork], Optional[TextVersion]]:
    """Return (work, version) when the version belongs to the slug's work."""
    work = get_text_work_by_slug(_texts_session(), slug)
    if work is None:
        return None, None
    version = get_text_version_by_id(_texts_session(), version_id)
    if version is None or version.work_id != work.id:
        return work, None
    return work, version


@bp.route("/<path:slug>/versions/<int:version_id>/edit")
def edit_version(slug: str, version_id: int) -> ResponseReturnValue:
    """Render the edit form for one version of a work."""
    if _is_readonly():
        flash("Cannot edit texts in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work, version = _get_version_for_work(slug, version_id)
    if work is None or version is None:
        flash("No such version.", "error")
        return redirect(
            url_for("texts.detail", slug=slug) if work else url_for("texts.list_texts_view")
        )

    return render_template(
        "texts/version_form.html",
        work=work,
        version=version,
        license_choices=CANONICAL_LICENSE_CHOICES,
    )


@bp.route("/<path:slug>/versions/<int:version_id>/update", methods=["POST"])
def update_version(slug: str, version_id: int) -> ResponseReturnValue:
    """Apply edits to a version (body, difficulty, source/license, verified)."""
    if _is_readonly():
        flash("Cannot edit texts in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work, version = _get_version_for_work(slug, version_id)
    if work is None or version is None:
        flash("No such version.", "error")
        return redirect(
            url_for("texts.detail", slug=slug) if work else url_for("texts.list_texts_view")
        )

    try:
        difficulty_level = _parse_difficulty(request.form.get("difficulty", ""))
    except ValueError:
        flash("Difficulty must be a whole number (or blank).", "error")
        return redirect(url_for("texts.edit_version", slug=slug, version_id=version_id))

    updated = update_text_version(
        _texts_session(),
        version,
        body=request.form.get("body", ""),
        difficulty_level=difficulty_level,
        text_source=request.form.get("text_source", "").strip(),
        license=request.form.get("license", "").strip() or None,
        verified=request.form.get("verified") == "1",
        notes=request.form.get("notes", "").strip(),
    )
    if updated is None:
        flash(
            "Failed to update the version (occupied difficulty slot, or a "
            "canonical version cannot lose its license).",
            "error",
        )
        return redirect(url_for("texts.edit_version", slug=slug, version_id=version_id))

    flash("Version updated.", "success")
    return redirect(url_for("texts.detail", slug=work.slug))


@bp.route("/<path:slug>/versions/<int:version_id>/delete", methods=["POST"])
def delete_version(slug: str, version_id: int) -> ResponseReturnValue:
    """Delete one version of a work."""
    if _is_readonly():
        flash("Cannot delete in read-only mode", "error")
        return redirect(url_for("texts.detail", slug=slug))

    work, version = _get_version_for_work(slug, version_id)
    if work is None or version is None:
        flash("No such version.", "error")
        return redirect(
            url_for("texts.detail", slug=slug) if work else url_for("texts.list_texts_view")
        )

    delete_text_version(_texts_session(), version)
    flash("Deleted the version.", "success")
    return redirect(url_for("texts.detail", slug=work.slug))
