"""Chinese grammatical/function-word data.

Includes structural particles, aspect markers, modal particles,
prepositions (coverbs), conjunctions, and basic adverbs that function
as grammatical markers.  Measure words are excluded even when they
have no clean English equivalent.
"""

from typing import Final

CHINESE_GRAMMATICAL_WORDS: Final[frozenset[str]] = frozenset(
    {
        # Structural particles
        "的",
        "地",
        "得",
        # Aspect / tense particles
        "了",
        "着",
        "过",
        # Sentence-final / modal particles
        "吗",
        "呢",
        "吧",
        "啊",
        "呀",
        "嘛",
        "哦",
        "啦",
        "吧",
        "嘛",
        # Pronouns
        "我",
        "你",
        "他",
        "她",
        "它",
        "我们",
        "你们",
        "他们",
        "她们",
        "自己",
        "这",
        "那",
        "哪",
        "谁",
        "什么",
        "哪里",
        "哪儿",
        "这里",
        "那里",
        "这儿",
        "那儿",
        # Determiners / quantifiers
        "每",
        "各",
        "某",
        "些",
        "这些",
        "那些",
        # Plural marker
        "们",
        # Prepositions (coverbs)
        "在",
        "从",
        "到",
        "向",
        "往",
        "对",
        "给",
        "把",
        "被",
        "让",
        "跟",
        "比",
        "为",
        "用",
        "按",
        "离",
        "沿",
        "关于",
        # Conjunctions
        "和",
        "与",
        "或",
        "或者",
        "但",
        "但是",
        "而",
        "而且",
        "因为",
        "所以",
        "如果",
        "虽然",
        "虽",
        "虽说",
        "尽管",
        "不但",
        "不仅",
        "既",
        # Negation
        "不",
        "没",
        "没有",
        "别",
        "未",
        "非",
        # Adverbial grammatical markers
        "就",
        "都",
        "也",
        "还",
        "又",
        "再",
        "才",
        "只",
        "很",
        "太",
        "最",
        "更",
        "已",
        "已经",
        "正",
        "正在",
        "刚",
        "刚才",
        "常",
        "常常",
        "总",
        "总是",
        # Existence / possession
        "有",
        # Copula
        "是",
        # Auxiliary
        "会",
        "能",
        "可以",
        "要",
        "应该",
        "得",
        "该",
        "必须",
        "想",
    }
)
