"""English grammatical/function-word data."""

from typing import Final

ENGLISH_GRAMMATICAL_WORDS_BY_CATEGORY: Final[dict[str, list[str]]] = {
    "pronouns": [
        "I",
        "me",
        "my",
        "myself",
        "we",
        "us",
        "our",
        "ours",
        "ourselves",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        "he",
        "him",
        "his",
        "himself",
        "she",
        "her",
        "hers",
        "herself",
        "it",
        "its",
        "itself",
        "they",
        "them",
        "their",
        "theirs",
        "themselves",
        "who",
        "whom",
        "whose",
        "which",
        "what",
        "that",
    ],
    "auxiliary_verbs": [
        "am",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "shall",
        "will",
        "should",
        "would",
        "may",
        "might",
        "must",
        "can",
        "could",
    ],
    "prepositions": [
        "at",
        "by",
        "for",
        "from",
        "in",
        "into",
        "of",
        "off",
        "on",
        "onto",
        "out",
        "over",
        "to",
        "under",
        "up",
        "with",
        "about",
        "above",
        "after",
        "before",
        "between",
        "during",
        "through",
        "upon",
        "without",
    ],
    "conjunctions": [
        "and",
        "but",
        "if",
        "or",
        "because",
        "as",
        "until",
        "while",
        "though",
        "so",
        "than",
        "since",
        "till",
        "nor",
    ],
    "determiners": [
        "a",
        "an",
        "the",
        "this",
        "that",
        "these",
        "those",
        "some",
        "all",
        "any",
        "every",
        "no",
        "such",
        "another",
        "each",
        "either",
        "neither",
    ],
}

ENGLISH_GRAMMATICAL_CONTRACTIONS: Final[list[str]] = [
    "don't",
    "doesn't",
    "didn't",
    "can't",
    "couldn't",
    "won't",
    "wouldn't",
    "isn't",
    "aren't",
    "wasn't",
    "weren't",
    "haven't",
    "hasn't",
    "hadn't",
    "I'm",
    "I'll",
    "I've",
    "I'd",
    "you're",
    "you'll",
    "you've",
    "he's",
    "she's",
    "it's",
    "we're",
    "we've",
    "they're",
    "what's",
    "where's",
    "who's",
    "that's",
    "there's",
    "here's",
    "let's",
    "that'll",
    "ain't",
]

ENGLISH_GRAMMATICAL_WORDS: Final[frozenset[str]] = frozenset(
    word.lower()
    for category_words in ENGLISH_GRAMMATICAL_WORDS_BY_CATEGORY.values()
    for word in category_words
)
ENGLISH_GRAMMATICAL_WORDS_WITH_CONTRACTIONS: Final[frozenset[str]] = frozenset(
    ENGLISH_GRAMMATICAL_WORDS | {word.lower() for word in ENGLISH_GRAMMATICAL_CONTRACTIONS}
)
