#!/usr/bin/python3
"""Gemini 3.8 text-to-speech client.

Uses the Gemini Interactions API, which returns encoded audio in a model-output
content block.  The model-qualified voice identifiers used by Greenland keep
audio generated by Flash and Flash-Lite in separate review/storage paths.
"""

import base64
import binascii
import logging
import time
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import requests

import clients.lib
from clients.keys import load_key

from .openai_tts import get_instructions
from .types import AudioFormat, AudioGenerationResult

logger = logging.getLogger(__name__)

API_URL = "https://generativelanguage.googleapis.com/v1beta/interactions"
DEFAULT_TIMEOUT = 120
GEMINI_38_FLASH_TTS = "gemini-3.8-flash-tts"
GEMINI_38_FLASH_LITE_TTS = "gemini-3.8-flash-lite-tts"
GEMINI_TTS_MODELS = (GEMINI_38_FLASH_TTS, GEMINI_38_FLASH_LITE_TTS)

# Gemini 3.8 Flash supports every tier 1-3 language.  Flash-Lite's published
# table omits Lithuanian, Swedish, Thai, and Swahili.  Spanish presentation and
# storage dialects use the same Spanish model capability with dialect prompts.
GEMINI_38_FLASH_TTS_LANGUAGES = frozenset(
    {
        "lt",
        "zh",
        "fr",
        "es",
        "de",
        "it",
        "nl",
        "pt",
        "sv",
        "vi",
        "ja",
        "ko",
        "ro",
        "pl",
        "th",
        "ta",
        "kn",
        "uk",
        "bn",
        "sw",
        "hi",
        "pa",
        "es-mx",
        "es-419",
        "zh-tw",
        "pt-br",
    }
)
GEMINI_38_FLASH_LITE_TTS_LANGUAGES = GEMINI_38_FLASH_TTS_LANGUAGES - {
    "lt",
    "sv",
    "th",
    "sw",
}

GEMINI_FORMAT_MAP: Dict[AudioFormat, str] = {
    AudioFormat.MP3: "audio/mp3",
    AudioFormat.WAV: "audio/wav",
    AudioFormat.OPUS: "audio/ogg_opus",
}


class GeminiTtsVoice(Enum):
    """Gemini's 30 prebuilt studio voices.

    Each value contains the API voice name, perceived gender, and Google's
    short style description.
    """

    ZEPHYR = ("Zephyr", "f", "Bright")
    PUCK = ("Puck", "m", "Upbeat")
    CHARON = ("Charon", "m", "Informative")
    KORE = ("Kore", "f", "Firm")
    FENRIR = ("Fenrir", "m", "Excitable")
    LEDA = ("Leda", "f", "Youthful")
    ORUS = ("Orus", "m", "Firm")
    AOEDE = ("Aoede", "f", "Breezy")
    CALLIRRHOE = ("Callirrhoe", "f", "Easy-going")
    AUTONOE = ("Autonoe", "f", "Bright")
    ENCELADUS = ("Enceladus", "m", "Breathy")
    IAPETUS = ("Iapetus", "m", "Clear")
    UMBRIEL = ("Umbriel", "m", "Easy-going")
    ALGIEBA = ("Algieba", "m", "Smooth")
    DESPINA = ("Despina", "f", "Smooth")
    ERINOME = ("Erinome", "f", "Clear")
    ALGENIB = ("Algenib", "m", "Gravelly")
    RASALGETHI = ("Rasalgethi", "m", "Informative")
    LAOMEDEIA = ("Laomedeia", "f", "Upbeat")
    ACHERNAR = ("Achernar", "f", "Soft")
    ALNILAM = ("Alnilam", "m", "Firm")
    SCHEDAR = ("Schedar", "m", "Even")
    GACRUX = ("Gacrux", "f", "Mature")
    PULCHERRIMA = ("Pulcherrima", "f", "Forward")
    ACHIRD = ("Achird", "m", "Friendly")
    ZUBENELGENUBI = ("Zubenelgenubi", "m", "Casual")
    VINDEMIATRIX = ("Vindemiatrix", "f", "Gentle")
    SADACHBIA = ("Sadachbia", "m", "Lively")
    SADALTAGER = ("Sadaltager", "m", "Knowledgeable")
    SULAFAT = ("Sulafat", "f", "Warm")

    @property
    def voice_name(self) -> str:
        return str(self.value[0])

    @property
    def gender(self) -> str:
        return str(self.value[1])

    @property
    def description(self) -> str:
        return str(self.value[2])

    def storage_name(self, model: str) -> str:
        """Return a model-qualified path/review name."""
        return f"{model}-{self.voice_name.lower()}"

    @classmethod
    def from_identifier(cls, identifier: str) -> Optional["GeminiTtsVoice"]:
        """Resolve a bare, enum, or model-qualified voice identifier."""
        normalized_identifier = identifier.lower()
        for gemini_voice in cls:
            valid_identifiers = {
                gemini_voice.name.lower(),
                gemini_voice.voice_name.lower(),
                gemini_voice.storage_name(GEMINI_38_FLASH_TTS),
                gemini_voice.storage_name(GEMINI_38_FLASH_LITE_TTS),
            }
            if normalized_identifier in valid_identifiers:
                return gemini_voice
        return None

    @classmethod
    def get_voices_for_language(cls, language_code: str, model: str) -> List["GeminiTtsVoice"]:
        """Return prebuilt voices when the model supports the language."""
        supported_languages = get_supported_languages(model)
        return list(cls) if language_code.lower() in supported_languages else []


def get_supported_languages(model: str) -> frozenset[str]:
    """Return the configured tier 1-3 languages supported by a Gemini model."""
    if model == GEMINI_38_FLASH_TTS:
        return GEMINI_38_FLASH_TTS_LANGUAGES
    if model == GEMINI_38_FLASH_LITE_TTS:
        return GEMINI_38_FLASH_LITE_TTS_LANGUAGES
    raise ValueError(f"Unsupported Gemini TTS model: {model}")


def _extract_audio(response_data: Dict[str, Any]) -> Tuple[bytes, Optional[str]]:
    """Extract the last inline audio block from an Interactions response."""
    steps = response_data.get("steps", [])
    for step in reversed(steps):
        content_blocks = step.get("content", []) if isinstance(step, dict) else []
        for content_block in reversed(content_blocks):
            if isinstance(content_block, dict) and content_block.get("type") == "audio":
                encoded_audio = content_block.get("data")
                if isinstance(encoded_audio, str) and encoded_audio:
                    return base64.b64decode(encoded_audio), content_block.get("mime_type")
    raise ValueError("Gemini TTS response did not contain inline audio data")


class GeminiTTSClient:
    """Generate single-speaker audio with Gemini 3.8 TTS."""

    def __init__(
        self,
        timeout: int = DEFAULT_TIMEOUT,
        debug: bool = False,
        api_key: Optional[str] = None,
    ) -> None:
        self.timeout = timeout
        self.debug = debug
        self.api_key = api_key if api_key else load_key("google", required=False)
        if debug:
            logger.setLevel(logging.DEBUG)

    def generate_audio(
        self,
        text: str,
        voice: GeminiTtsVoice = GeminiTtsVoice.KORE,
        language_code: str = "es",
        model: str = GEMINI_38_FLASH_TTS,
        audio_format: AudioFormat = AudioFormat.MP3,
        is_sentence: bool = False,
    ) -> AudioGenerationResult:
        """Generate audio using the Gemini Interactions API."""
        if not self.api_key:
            return self._error_result(text, language_code, model, "Gemini API key not available")
        if model not in GEMINI_TTS_MODELS:
            return self._error_result(text, language_code, model, f"Unsupported model: {model}")
        if language_code.lower() not in get_supported_languages(model):
            return self._error_result(
                text,
                language_code,
                model,
                f"{model} does not support language '{language_code}'",
            )
        mime_type = GEMINI_FORMAT_MAP.get(audio_format)
        if mime_type is None:
            return self._error_result(
                text, language_code, model, f"Unsupported audio format: {audio_format.value}"
            )

        clients.lib.assert_llm_calls_enabled("gemini-tts")
        style = get_instructions(language_code, is_sentence=is_sentence)
        payload: Dict[str, Any] = {
            "model": model,
            "input": [
                {
                    "type": "user_input",
                    "content": [
                        {
                            "type": "text",
                            "text": text,
                            "annotations": [{"type": "speech_metadata", "style": style}],
                        }
                    ],
                }
            ],
            "response_format": {"type": "audio", "mime_type": mime_type},
            "generation_config": {"speech_config": [{"voice": voice.voice_name}]},
            "store": False,
        }
        headers = {"Content-Type": "application/json", "x-goog-api-key": self.api_key}
        start_time = time.time()
        try:
            response = requests.post(API_URL, headers=headers, json=payload, timeout=self.timeout)
            if response.status_code != 200:
                return self._error_result(
                    text,
                    language_code,
                    model,
                    f"Gemini TTS API error {response.status_code}: {response.text}",
                )
            audio_data, response_mime_type = _extract_audio(response.json())
            if self.debug:
                logger.debug(
                    "Gemini TTS returned %d bytes as %s",
                    len(audio_data),
                    response_mime_type,
                )
            return AudioGenerationResult(
                audio_data=audio_data,
                text=text,
                voice=None,
                language_code=language_code,
                model=model,
                duration_ms=(time.time() - start_time) * 1000,
            )
        except (requests.RequestException, ValueError, KeyError, binascii.Error) as exc:
            return self._error_result(text, language_code, model, f"Gemini TTS error: {exc}")

    @staticmethod
    def _error_result(
        text: str, language_code: str, model: str, error: str
    ) -> AudioGenerationResult:
        logger.error(error)
        return AudioGenerationResult(
            audio_data=b"",
            text=text,
            voice=None,
            language_code=language_code,
            model=model,
            duration_ms=0,
            success=False,
            error=error,
        )
