#!/usr/bin/python3

"""Client for querying LLMs for linguistic information about words."""

import logging
import threading
from typing import Any, Dict, List, Optional, Tuple, Union

import constants
from clients.unified_client import UnifiedLLMClient
from storage.backend.config import BackendType, DataSourceConfig
from storage.backend import create_session

# Import specialized modules
from wordfreq.translation import (
    definitions,
    translations,
    word_processing,
)
from wordfreq.translation.constants import DEFAULT_MODEL

# Word forms are generated by langtools.form_tasks.generate_forms, not here.

# Configure logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


class LinguisticClient:
    """Client for querying LLMs for linguistic information."""

    # Thread-local storage for client instances
    _thread_local = threading.local()

    def __init__(
        self,
        config: Optional[Union[DataSourceConfig, str]] = None,
        model: Optional[str] = None,
        db_path: Optional[str] = None,
        debug: bool = False,
    ) -> None:
        """
        Initialize client with configuration or legacy parameters.

        Args:
            config: DataSourceConfig object (preferred) OR string db_path (legacy)
            model: Model name to use for queries (ignored if config provided)
            db_path: Path to the SQLite database (legacy, use config instead)
            debug: Whether to enable debug logging (ignored if config provided)

        Examples:
            # New style (preferred):
            client = LinguisticClient(config=data_source_config)

            # Legacy style (backward compatible):
            client = LinguisticClient(model="gpt-4", db_path="/path/to/db")
            client = LinguisticClient(db_path="/path/to/db")  # config as positional arg
        """
        # Handle backward compatibility: config can be a string (db_path)
        if isinstance(config, str):
            db_path = config
            config = None

        # Extract values from config or use legacy parameters
        if isinstance(config, DataSourceConfig):
            self.config = config
            self.model = config.model or DEFAULT_MODEL
            self.debug = config.debug
            # Extract db_path from config
            if config.backend_type == BackendType.SQLITE:
                self.db_path = config.sqlite_path or constants.WORDFREQ_DB_PATH
            else:
                self.db_path = constants.WORDFREQ_DB_PATH  # fallback
        else:
            # Legacy mode: use individual parameters
            self.model = model or DEFAULT_MODEL
            self.db_path = db_path or constants.WORDFREQ_DB_PATH
            self.debug = debug
            self.config = DataSourceConfig(
                backend_type=BackendType.SQLITE,
                sqlite_path=self.db_path,
                model=self.model,
                debug=self.debug,
            )

        self.client = UnifiedLLMClient(debug=self.debug)
        self.client.default_model = self.model

        if self.debug:
            logger.setLevel(logging.DEBUG)

        # Warm up the model.  Callers build a client per request, so this runs
        # once per call: a no-op for the remote backends, a cheap state check
        # for a local model that is already loaded.  Success is therefore only
        # worth a DEBUG line; a False return means a local model did not load.
        try:
            if self.client.warm_model(self.model):
                logger.debug("Model %s warmed up", self.model)
            else:
                logger.warning("Model %s did not warm up", self.model)
        except Exception as e:
            logger.warning(f"Failed to warm up model {self.model}: {e}")

    def get_session(self) -> Any:
        """
        Get this thread's database session, creating it on first use.

        The session is owned by this thread-local client and reused across the
        many ``query_*`` helpers, which call this repeatedly and never close
        what they get back.  ``close_thread_session`` releases it; the worker
        loop calls that when the thread is done.

        Returns:
            This thread's database session
        """
        session = getattr(self._thread_local, "session", None)
        if session is None:
            session = create_session(self.config)
            self._thread_local.session = session
        return session

    @classmethod
    def close_thread_session(cls) -> None:
        """Close and drop this thread's session, if it opened one."""
        session = getattr(cls._thread_local, "session", None)
        if session is not None:
            session.close()
            cls._thread_local.session = None

    # Definition queries
    def query_definitions(
        self,
        word: str,
        example_sentence: Optional[str] = None,
        pos_type: Optional[str] = None,
    ) -> Tuple[List[Dict[str, Any]], bool]:
        """Query LLM for definitions, POS, and lemma information."""
        return definitions.query_definitions(
            self.client,
            word,
            self.get_session,
            self.model,
            example_sentence=example_sentence,
            pos_type=pos_type,
        )

    # Translation queries
    def query_translations(
        self,
        english_word: str,
        reference_translation: Tuple[str, str],
        definition: str,
        pos_type: str,
        pos_subtype: Optional[str] = None,
        languages: Optional[List[str]] = None,
    ) -> Tuple[Dict[str, Any], bool]:
        """
        Query LLM to generate translations for a word.

        Args:
            english_word: English lemma form
            reference_translation: Tuple of (language_code, translation) for context
            definition: Definition of the word
            pos_type: Part of speech
            pos_subtype: Optional POS subtype
            languages: List of language names to generate translations for

        Returns:
            Tuple of (translations dict, success flag)
        """
        return translations.query_translations(
            self.client,
            english_word,
            reference_translation,
            definition,
            pos_type,
            self.get_session,
            pos_subtype,
            languages,
            self.model,
        )

    # Word processing
    def process_word(self, word: str, refresh: bool = False) -> bool:
        """Process a word to get linguistic information and store in database."""
        return word_processing.process_word(self.client, word, self.get_session, refresh)
