#!/usr/bin/env python3
"""Import medication names: the WHO essential medicines, top sellers, and brands.

Assembled rather than mined, like the chemical elements at 1100.  These are
wanted less for teaching than for recognition: a drug name in a news article,
a court opinion or a parliamentary debate should resolve to a known lemma
instead of surfacing as an unknown token in every corpus survey.  The obscure
ones -- bedaquiline, odesivimab -- are the point, not a cost.

Three sources, in this order:

* ``WHO_ESSENTIAL`` -- the WHO Model List of Essential Medicines, 24th list
  (2025), as transcribed on the English Wikipedia article "WHO Model List of
  Essential Medicines" (fetched 2026-09-27), in the list's own section order so
  a reviewer can check it against the source.  Combination products are split
  into their ingredients ("lopinavir/ritonavir" gives both), and salt suffixes
  are dropped ("heparin sodium" is heparin).  Left out: vaccines, blood
  products, immunoglobulins, devices, solutions and nutrition products, and the
  entries that are ordinary vocabulary or chemistry rather than drug names
  (oxygen, glucose, urea, ethanol, iodine, magnesium sulfate, activated
  charcoal).
* ``US_PRESCRIBED`` -- the most-prescribed drugs in the United States (the
  ClinCalc / MEPS top 200), less what the WHO list already has.
* ``TOP_REVENUE`` -- the world's best-selling drugs by revenue, less both of the
  above.  Mostly biologics and targeted cancer drugs, so this is where most of
  the -mab and -nib names come from.

Spellings are American (USAN), not INN, for the reason the elements list gives:
this database is American-spelled, and an INN spelling beside an existing USAN
lemma would mint a second lemma for the same drug.  So acyclovir, rifampin,
cephalexin, albuterol, nitroglycerin, leuprolide and scopolamine rather than
aciclovir, rifampicin, cefalexin, salbutamol, glyceryl trinitrate, leuprorelin
and hyoscine.  Two WHO entries are left out as already lemmas at 450:
acetylsalicylic acid, as "aspirin", and paracetamol.  (Its American name,
acetaminophen, is deliberately not added; it would duplicate that lemma.)

Generic names go through ``add_word``: sense discovery handles a single-sense
technical noun well, and supplies the definition and translations.  Brand
names go through ``add_term`` as :class:`TermEntry` rows, because asked what
"Lipitor" means the model would answer "atorvastatin" and file it there.  Each
brand is its own lemma -- one per brand, not per product line -- with a
definition naming its generic, and is tagged ``medications``.  Brands are
proper nouns and keep their capitals.

Not pre-deduplicated against the database; the preflight skips what is already
accounted for.  When the list was drawn up only testosterone was -- as a
chemical compound at 1050 -- so even insulin, morphine and caffeine are new.

Running without ``--execute`` only prints the plan and makes no HTTP requests.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Sequence

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.wordlist_import_helper import TermEntry, run_mixed_import

DIFFICULTY_LEVEL = 1140

TAGS: Sequence[str] = ("medications",)

WHO_ESSENTIAL: Sequence[str] = (
    # Anesthetics, preoperative medicines and medical gases
    "isoflurane",
    "nitrous oxide",
    "sevoflurane",
    "ketamine",
    "propofol",
    "bupivacaine",
    "lidocaine",
    "epinephrine",
    "ephedrine",
    "atropine",
    "midazolam",
    # Pain and palliative care
    "morphine",
    "ibuprofen",
    "codeine",
    "fentanyl",
    "methadone",
    "amitriptyline",
    "cyclizine",
    "dexamethasone",
    "diazepam",
    "docusate",
    "fluoxetine",
    "haloperidol",
    "scopolamine",
    "lactulose",
    "loperamide",
    "metoclopramide",
    "ondansetron",
    "senna",
    # Antiallergics
    "hydrocortisone",
    "loratadine",
    "prednisolone",
    # Antidotes
    "acetylcysteine",
    "methylene blue",
    "naloxone",
    "penicillamine",
    "deferoxamine",
    "dimercaprol",
    "fomepizole",
    "succimer",
    # Anticonvulsants
    "carbamazepine",
    "lamotrigine",
    "levetiracetam",
    "lorazepam",
    "phenobarbital",
    "phenytoin",
    "valproic acid",
    "ethosuximide",
    # Multiple sclerosis, Parkinson's, migraine
    "cladribine",
    "glatiramer",
    "rituximab",
    "biperiden",
    "levodopa",
    "carbidopa",
    "baclofen",
    "sumatriptan",
    "propranolol",
    "verapamil",
    # Antibacterials
    "amoxicillin",
    "ampicillin",
    "penicillin G",
    "cefotaxime",
    "ceftriaxone",
    "chloramphenicol",
    "gentamicin",
    "meropenem",
    "amikacin",
    "clavulanic acid",
    "cephalexin",
    "cefazolin",
    "clindamycin",
    "cloxacillin",
    "doxycycline",
    "metronidazole",
    "nitrofurantoin",
    "penicillin V",
    "spectinomycin",
    "sulfamethoxazole",
    "trimethoprim",
    "azithromycin",
    "cefixime",
    "cefuroxime",
    "ciprofloxacin",
    "clarithromycin",
    "piperacillin",
    "tazobactam",
    "vancomycin",
    "ceftazidime",
    "cefiderocol",
    "avibactam",
    "ceftolozane",
    "colistin",
    "fosfomycin",
    "linezolid",
    "vaborbactam",
    "plazomicin",
    "polymyxin",
    # Leprosy and tuberculosis
    "clofazimine",
    "dapsone",
    "rifampin",
    "bedaquiline",
    "cycloserine",
    "delamanid",
    "ethambutol",
    "isoniazid",
    "pyrazinamide",
    "ethionamide",
    "rifapentine",
    "levofloxacin",
    "moxifloxacin",
    "pretomanid",
    "rifabutin",
    "streptomycin",
    # Antifungals
    "amphotericin",
    "clotrimazole",
    "fluconazole",
    "flucytosine",
    "griseofulvin",
    "itraconazole",
    "nystatin",
    "voriconazole",
    "micafungin",
    # Antivirals
    "acyclovir",
    "abacavir",
    "lamivudine",
    "tenofovir",
    "zidovudine",
    "efavirenz",
    "nevirapine",
    "atazanavir",
    "ritonavir",
    "darunavir",
    "lopinavir",
    "dolutegravir",
    "raltegravir",
    "emtricitabine",
    "valganciclovir",
    "oseltamivir",
    "entecavir",
    "daclatasvir",
    "sofosbuvir",
    "glecaprevir",
    "pibrentasvir",
    "ravidasvir",
    "velpatasvir",
    "ledipasvir",
    "ribavirin",
    # Anthelminthics
    "albendazole",
    "ivermectin",
    "levamisole",
    "mebendazole",
    "niclosamide",
    "praziquantel",
    "pyrantel",
    "diethylcarbamazine",
    "triclabendazole",
    "oxamniquine",
    # Antiprotozoals and antimalarials
    "diloxanide",
    "miltefosine",
    "paromomycin",
    "stibogluconate",
    "artemether",
    "lumefantrine",
    "artesunate",
    "amodiaquine",
    "mefloquine",
    "pyronaridine",
    "chloroquine",
    "dihydroartemisinin",
    "piperaquine",
    "primaquine",
    "quinine",
    "sulfadoxine",
    "pyrimethamine",
    "sulfadiazine",
    "pentamidine",
    "fexinidazole",
    "suramin",
    "eflornithine",
    "melarsoprol",
    "nifurtimox",
    "benznidazole",
    # Ebola and cystic fibrosis
    "ansuvimab",
    "atoltivimab",
    "maftivimab",
    "odesivimab",
    "elexacaftor",
    "tezacaftor",
    "ivacaftor",
    "pancrelipase",
    # Immunomodulators and antineoplastics
    "adalimumab",
    "azathioprine",
    "cyclosporine",
    "tacrolimus",
    "asparaginase",
    "bendamustine",
    "bleomycin",
    "leucovorin",
    "capecitabine",
    "carboplatin",
    "chlorambucil",
    "cisplatin",
    "cyclophosphamide",
    "cytarabine",
    "dacarbazine",
    "dactinomycin",
    "daunorubicin",
    "docetaxel",
    "doxorubicin",
    "etoposide",
    "fludarabine",
    "fluorouracil",
    "gemcitabine",
    "hydroxyurea",
    "ifosfamide",
    "irinotecan",
    "melphalan",
    "mercaptopurine",
    "methotrexate",
    "oxaliplatin",
    "paclitaxel",
    "pegaspargase",
    "procarbazine",
    "thioguanine",
    "vinblastine",
    "vincristine",
    "vinorelbine",
    "tretinoin",
    "bortezomib",
    "dasatinib",
    "erlotinib",
    "everolimus",
    "ibrutinib",
    "imatinib",
    "nilotinib",
    "trastuzumab",
    "blinatumomab",
    "filgrastim",
    "lenalidomide",
    "pegfilgrastim",
    "pembrolizumab",
    "thalidomide",
    "abiraterone",
    "anastrozole",
    "bicalutamide",
    "leuprolide",
    "methylprednisolone",
    "tamoxifen",
    "allopurinol",
    "mesna",
    "rasburicase",
    "zoledronic acid",
    # Blood
    "folic acid",
    "hydroxocobalamin",
    "dabigatran",
    "desmopressin",
    "emicizumab",
    "enoxaparin",
    "heparin",
    "phytonadione",
    "protamine",
    "tranexamic acid",
    "warfarin",
    "deferasirox",
    # Cardiovascular
    "bisoprolol",
    "nitroglycerin",
    "isosorbide",
    "digoxin",
    "amiodarone",
    "amlodipine",
    "enalapril",
    "hydralazine",
    "hydrochlorothiazide",
    "lisinopril",
    "losartan",
    "methyldopa",
    "perindopril",
    "indapamide",
    "telmisartan",
    "valsartan",
    "nitroprusside",
    "furosemide",
    "spironolactone",
    "clopidogrel",
    "alteplase",
    "streptokinase",
    "simvastatin",
    "atorvastatin",
    "ramipril",
    "atenolol",
    # Dermatological
    "miconazole",
    "terbinafine",
    "mupirocin",
    "betamethasone",
    "calamine",
    "benzoyl peroxide",
    "calcipotriene",
    "salicylic acid",
    "ustekinumab",
    "permethrin",
    # Diagnostic agents, antiseptics and disinfectants
    "fluorescein",
    "tropicamide",
    "diatrizoate",
    "iohexol",
    "chlorhexidine",
    "povidone-iodine",
    "chloroxylenol",
    "glutaraldehyde",
    # Diuretics and gastrointestinal
    "amiloride",
    "mannitol",
    "omeprazole",
    "ranitidine",
    "aprepitant",
    "sulfasalazine",
    # Hormones and endocrine
    "fludrocortisone",
    "testosterone",
    "medroxyprogesterone",
    "insulin",
    "empagliflozin",
    "gliclazide",
    "metformin",
    "semaglutide",
    "glucagon",
    "diazoxide",
    "levothyroxine",
    "methimazole",
    "propylthiouracil",
    "cabergoline",
    "octreotide",
    "tuberculin",
    # Muscle relaxants and ophthalmology
    "atracurium",
    "succinylcholine",
    "vecuronium",
    "erythromycin",
    "natamycin",
    "ofloxacin",
    "tetracycline",
    "tetracaine",
    "acetazolamide",
    "latanoprost",
    "pilocarpine",
    "timolol",
    "bevacizumab",
    # Reproductive health and perinatal care
    "ethinyl estradiol",
    "levonorgestrel",
    "norethindrone",
    "ulipristal",
    "estradiol",
    "etonogestrel",
    "progesterone",
    "clomiphene",
    "letrozole",
    "carbetocin",
    "ergonovine",
    "misoprostol",
    "oxytocin",
    "mifepristone",
    "nifedipine",
    "caffeine",
    "alprostadil",
    "beractant",
    "poractant",
    # Mental and behavioral disorders
    "fluphenazine",
    "olanzapine",
    "paliperidone",
    "risperidone",
    "clozapine",
    "quetiapine",
    "clomipramine",
    "acamprosate",
    "naltrexone",
    "bupropion",
    "cytisine",
    "varenicline",
    # Respiratory
    "budesonide",
    "formoterol",
    "ipratropium",
    "albuterol",
    "tiotropium",
    # Vitamins
    "ascorbic acid",
    "cholecalciferol",
    "ergocalciferol",
    "nicotinamide",
    "pyridoxine",
    "retinol",
    "riboflavin",
    "thiamine",
    # Ear, nose and throat; joints
    "xylometazoline",
    "hydroxychloroquine",
    "triamcinolone",
)

US_PRESCRIBED: Sequence[str] = (
    # Cardiovascular and metabolic
    "metoprolol",
    "rosuvastatin",
    "pravastatin",
    "carvedilol",
    "apixaban",
    "rivaroxaban",
    "clonidine",
    "diltiazem",
    "olmesartan",
    "irbesartan",
    "benazepril",
    "nebivolol",
    "labetalol",
    "chlorthalidone",
    "triamterene",
    "bumetanide",
    "torsemide",
    "sacubitril",
    "ticagrelor",
    "ezetimibe",
    "fenofibrate",
    "glipizide",
    "glimepiride",
    "pioglitazone",
    "sitagliptin",
    "linagliptin",
    "dapagliflozin",
    "canagliflozin",
    "dulaglutide",
    "liraglutide",
    "tirzepatide",
    "insulin glargine",
    "insulin lispro",
    "insulin aspart",
    "insulin detemir",
    "liothyronine",
    "alendronate",
    "raloxifene",
    "colchicine",
    "febuxostat",
    # Pain, muscle and sleep
    "gabapentin",
    "pregabalin",
    "tramadol",
    "oxycodone",
    "hydrocodone",
    "hydromorphone",
    "buprenorphine",
    "meloxicam",
    "celecoxib",
    "diclofenac",
    "naproxen",
    "ketorolac",
    "cyclobenzaprine",
    "methocarbamol",
    "tizanidine",
    "carisoprodol",
    "butalbital",
    "rizatriptan",
    "zolpidem",
    "temazepam",
    # Psychiatric and neurological
    "sertraline",
    "escitalopram",
    "citalopram",
    "paroxetine",
    "duloxetine",
    "venlafaxine",
    "desvenlafaxine",
    "vortioxetine",
    "trazodone",
    "mirtazapine",
    "nortriptyline",
    "doxepin",
    "buspirone",
    "alprazolam",
    "clonazepam",
    "hydroxyzine",
    "aripiprazole",
    "ziprasidone",
    "lurasidone",
    "amphetamine",
    "dextroamphetamine",
    "lisdexamfetamine",
    "methylphenidate",
    "dexmethylphenidate",
    "atomoxetine",
    "guanfacine",
    "topiramate",
    "divalproex",
    "oxcarbazepine",
    "lacosamide",
    "donepezil",
    "memantine",
    "ropinirole",
    # Respiratory, allergy and cold
    "montelukast",
    "fluticasone",
    "salmeterol",
    "mometasone",
    "cetirizine",
    "levocetirizine",
    "fexofenadine",
    "diphenhydramine",
    "pseudoephedrine",
    "guaifenesin",
    "dextromethorphan",
    "benzonatate",
    # Gastrointestinal
    "pantoprazole",
    "esomeprazole",
    "famotidine",
    "sucralfate",
    "dicyclomine",
    "bisacodyl",
    "bismuth subsalicylate",
    "promethazine",
    "prochlorperazine",
    "meclizine",
    "dimenhydrinate",
    # Urology, dermatology and infection
    "tamsulosin",
    "finasteride",
    "oxybutynin",
    "sildenafil",
    "tadalafil",
    "clobetasol",
    "valacyclovir",
    "prednisone",
)

TOP_REVENUE: Sequence[str] = (
    # Immunology
    "etanercept",
    "infliximab",
    "certolizumab",
    "golimumab",
    "abatacept",
    "tocilizumab",
    "secukinumab",
    "ixekizumab",
    "guselkumab",
    "risankizumab",
    "upadacitinib",
    "tofacitinib",
    "apremilast",
    "dupilumab",
    "omalizumab",
    "mepolizumab",
    "benralizumab",
    "tezepelumab",
    "vedolizumab",
    "ocrelizumab",
    "natalizumab",
    "fingolimod",
    "ozanimod",
    "eculizumab",
    "ravulizumab",
    # Oncology
    "nivolumab",
    "atezolizumab",
    "durvalumab",
    "pertuzumab",
    "daratumumab",
    "osimertinib",
    "palbociclib",
    "abemaciclib",
    "olaparib",
    "enzalutamide",
    "acalabrutinib",
    "zanubrutinib",
    "venetoclax",
    "ruxolitinib",
    "pomalidomide",
    # Eye, bone, cardiovascular and blood
    "aflibercept",
    "ranibizumab",
    "faricimab",
    "denosumab",
    "romosozumab",
    "teriparatide",
    "evolocumab",
    "epoetin",
    "darbepoetin",
    # Neurology and psychiatry
    "erenumab",
    "galcanezumab",
    "fremanezumab",
    "rimegepant",
    "ubrogepant",
    "lecanemab",
    "nusinersen",
    "tafamidis",
    "valbenazine",
    "cariprazine",
    "brexpiprazole",
    # Infectious disease and other
    "bictegravir",
    "nirmatrelvir",
    "mirabegron",
    "linaclotide",
)


def _brand(name: str, definition: str) -> TermEntry:
    return TermEntry(name, "noun", "medication_remedy", definition)


BRANDS: Sequence[TermEntry] = (
    # Cardiovascular and metabolic
    _brand("Lipitor", "a brand name for atorvastatin, a statin that lowers cholesterol"),
    _brand("Crestor", "a brand name for rosuvastatin, a statin that lowers cholesterol"),
    _brand("Zocor", "a brand name for simvastatin, a statin that lowers cholesterol"),
    _brand("Norvasc", "a brand name for amlodipine, a blood pressure medication"),
    _brand("Zestril", "a brand name for lisinopril, a blood pressure medication"),
    _brand("Lopressor", "a brand name for metoprolol, a beta blocker"),
    _brand("Coreg", "a brand name for carvedilol, a beta blocker"),
    _brand("Cozaar", "a brand name for losartan, a blood pressure medication"),
    _brand("Diovan", "a brand name for valsartan, a blood pressure medication"),
    _brand("Lasix", "a brand name for furosemide, a diuretic"),
    _brand("Aldactone", "a brand name for spironolactone, a diuretic"),
    _brand("Entresto", "a brand name for sacubitril and valsartan, a heart failure medication"),
    _brand("Plavix", "a brand name for clopidogrel, a drug that prevents blood clots"),
    _brand("Eliquis", "a brand name for apixaban, an anticoagulant"),
    _brand("Xarelto", "a brand name for rivaroxaban, an anticoagulant"),
    _brand("Coumadin", "a brand name for warfarin, an anticoagulant"),
    _brand("Lovenox", "a brand name for enoxaparin, an injected anticoagulant"),
    _brand("Synthroid", "a brand name for levothyroxine, a thyroid hormone"),
    _brand("Glucophage", "a brand name for metformin, a diabetes medication"),
    _brand("Januvia", "a brand name for sitagliptin, a diabetes medication"),
    _brand("Jardiance", "a brand name for empagliflozin, a diabetes medication"),
    _brand("Farxiga", "a brand name for dapagliflozin, a diabetes medication"),
    _brand("Lantus", "a brand name for insulin glargine, a long-acting insulin"),
    _brand("Humalog", "a brand name for insulin lispro, a rapid-acting insulin"),
    _brand("NovoLog", "a brand name for insulin aspart, a rapid-acting insulin"),
    _brand("Trulicity", "a brand name for dulaglutide, an injected diabetes medication"),
    _brand("Victoza", "a brand name for liraglutide, an injected diabetes medication"),
    _brand("Ozempic", "a brand name for semaglutide, an injected diabetes medication"),
    _brand("Wegovy", "a brand name for semaglutide, prescribed for weight loss"),
    _brand("Mounjaro", "a brand name for tirzepatide, an injected diabetes medication"),
    _brand("Zepbound", "a brand name for tirzepatide, prescribed for weight loss"),
    _brand("Repatha", "a brand name for evolocumab, an injected cholesterol drug"),
    # Pain, fever and inflammation
    _brand("Tylenol", "a brand name for acetaminophen (paracetamol), a pain reliever"),
    _brand("Panadol", "a brand name for paracetamol (acetaminophen), a pain reliever"),
    _brand("Advil", "a brand name for ibuprofen, a pain reliever"),
    _brand("Motrin", "a brand name for ibuprofen, a pain reliever"),
    _brand("Nurofen", "a brand name for ibuprofen, a pain reliever"),
    _brand("Aleve", "a brand name for naproxen, a pain reliever"),
    _brand("Celebrex", "a brand name for celecoxib, an anti-inflammatory drug"),
    _brand("Voltaren", "a brand name for diclofenac, an anti-inflammatory drug"),
    _brand("Ultram", "a brand name for tramadol, an opioid pain reliever"),
    _brand("OxyContin", "a brand name for extended-release oxycodone, an opioid"),
    _brand("Percocet", "a brand name for oxycodone with acetaminophen, an opioid"),
    _brand("Vicodin", "a brand name for hydrocodone with acetaminophen, an opioid"),
    _brand("Dilaudid", "a brand name for hydromorphone, an opioid"),
    _brand("Suboxone", "a brand name for buprenorphine with naloxone, for opioid addiction"),
    _brand("Narcan", "a brand name for naloxone, which reverses an opioid overdose"),
    _brand("Flexeril", "a brand name for cyclobenzaprine, a muscle relaxant"),
    _brand("Imitrex", "a brand name for sumatriptan, a migraine medication"),
    # Psychiatric and neurological
    _brand("Prozac", "a brand name for fluoxetine, an antidepressant"),
    _brand("Zoloft", "a brand name for sertraline, an antidepressant"),
    _brand("Paxil", "a brand name for paroxetine, an antidepressant"),
    _brand("Lexapro", "a brand name for escitalopram, an antidepressant"),
    _brand("Celexa", "a brand name for citalopram, an antidepressant"),
    _brand("Wellbutrin", "a brand name for bupropion, an antidepressant"),
    _brand("Cymbalta", "a brand name for duloxetine, an antidepressant"),
    _brand("Effexor", "a brand name for venlafaxine, an antidepressant"),
    _brand("Xanax", "a brand name for alprazolam, an anti-anxiety drug"),
    _brand("Valium", "a brand name for diazepam, a sedative"),
    _brand("Ativan", "a brand name for lorazepam, an anti-anxiety drug"),
    _brand("Klonopin", "a brand name for clonazepam, an anti-anxiety and anti-seizure drug"),
    _brand("Ambien", "a brand name for zolpidem, a sleeping pill"),
    _brand("Seroquel", "a brand name for quetiapine, an antipsychotic"),
    _brand("Abilify", "a brand name for aripiprazole, an antipsychotic"),
    _brand("Risperdal", "a brand name for risperidone, an antipsychotic"),
    _brand("Zyprexa", "a brand name for olanzapine, an antipsychotic"),
    _brand("Haldol", "a brand name for haloperidol, an antipsychotic"),
    _brand("Adderall", "a brand name for amphetamine salts, an ADHD medication"),
    _brand("Ritalin", "a brand name for methylphenidate, an ADHD medication"),
    _brand("Concerta", "a brand name for extended-release methylphenidate, for ADHD"),
    _brand("Vyvanse", "a brand name for lisdexamfetamine, an ADHD medication"),
    _brand("Neurontin", "a brand name for gabapentin, for nerve pain and seizures"),
    _brand("Lyrica", "a brand name for pregabalin, for nerve pain and seizures"),
    _brand("Lamictal", "a brand name for lamotrigine, an anti-seizure drug"),
    _brand("Depakote", "a brand name for divalproex, an anti-seizure drug"),
    _brand("Tegretol", "a brand name for carbamazepine, an anti-seizure drug"),
    _brand("Dilantin", "a brand name for phenytoin, an anti-seizure drug"),
    _brand("Keppra", "a brand name for levetiracetam, an anti-seizure drug"),
    _brand("Topamax", "a brand name for topiramate, an anti-seizure drug"),
    _brand("Aricept", "a brand name for donepezil, an Alzheimer's disease medication"),
    _brand("Namenda", "a brand name for memantine, an Alzheimer's disease medication"),
    _brand("Chantix", "a brand name for varenicline, a stop-smoking medication"),
    # Respiratory, allergy and cold
    _brand("Singulair", "a brand name for montelukast, an asthma and allergy medication"),
    _brand("Ventolin", "a brand name for albuterol, an asthma inhaler"),
    _brand("ProAir", "a brand name for albuterol, an asthma inhaler"),
    _brand("Flonase", "a brand name for fluticasone, a nasal allergy spray"),
    _brand("Advair", "a brand name for fluticasone with salmeterol, an asthma inhaler"),
    _brand("Symbicort", "a brand name for budesonide with formoterol, an asthma inhaler"),
    _brand("Spiriva", "a brand name for tiotropium, an inhaler for lung disease"),
    _brand("Benadryl", "a brand name for diphenhydramine, an antihistamine"),
    _brand("Claritin", "a brand name for loratadine, an antihistamine"),
    _brand("Zyrtec", "a brand name for cetirizine, an antihistamine"),
    _brand("Allegra", "a brand name for fexofenadine, an antihistamine"),
    _brand("Xyzal", "a brand name for levocetirizine, an antihistamine"),
    _brand("Sudafed", "a brand name for pseudoephedrine, a nasal decongestant"),
    _brand("Mucinex", "a brand name for guaifenesin, an expectorant"),
    _brand("Robitussin", "a brand name for a cough syrup of dextromethorphan or guaifenesin"),
    # Gastrointestinal
    _brand("Prilosec", "a brand name for omeprazole, an antacid medication"),
    _brand("Nexium", "a brand name for esomeprazole, an antacid medication"),
    _brand("Protonix", "a brand name for pantoprazole, an antacid medication"),
    _brand("Zantac", "a brand name for ranitidine, an antacid medication"),
    _brand("Pepcid", "a brand name for famotidine, an antacid medication"),
    _brand("Imodium", "a brand name for loperamide, an anti-diarrhea medication"),
    _brand("Pepto-Bismol", "a brand name for bismuth subsalicylate, for an upset stomach"),
    _brand("Dramamine", "a brand name for dimenhydrinate, for motion sickness"),
    _brand("Zofran", "a brand name for ondansetron, an anti-nausea drug"),
    _brand("Phenergan", "a brand name for promethazine, an anti-nausea drug"),
    # Infection
    _brand("Amoxil", "a brand name for amoxicillin, an antibiotic"),
    _brand("Augmentin", "a brand name for amoxicillin with clavulanic acid, an antibiotic"),
    _brand("Keflex", "a brand name for cephalexin, an antibiotic"),
    _brand("Zithromax", "a brand name for azithromycin, an antibiotic"),
    _brand("Cipro", "a brand name for ciprofloxacin, an antibiotic"),
    _brand("Levaquin", "a brand name for levofloxacin, an antibiotic"),
    _brand("Bactrim", "a brand name for sulfamethoxazole with trimethoprim, an antibiotic"),
    _brand("Flagyl", "a brand name for metronidazole, an antibiotic"),
    _brand("Diflucan", "a brand name for fluconazole, an antifungal"),
    _brand("Valtrex", "a brand name for valacyclovir, an antiviral for herpes"),
    _brand("Zovirax", "a brand name for acyclovir, an antiviral for herpes"),
    _brand("Tamiflu", "a brand name for oseltamivir, an antiviral for influenza"),
    _brand("Paxlovid", "a brand name for nirmatrelvir with ritonavir, for COVID-19"),
    _brand("Biktarvy", "a brand name for bictegravir, emtricitabine and tenofovir, for HIV"),
    _brand("Truvada", "a brand name for emtricitabine with tenofovir, for HIV"),
    _brand("Epclusa", "a brand name for sofosbuvir with velpatasvir, for hepatitis C"),
    _brand("Plaquenil", "a brand name for hydroxychloroquine, for malaria and lupus"),
    # Immunology
    _brand("Humira", "a brand name for adalimumab, for arthritis and bowel disease"),
    _brand("Enbrel", "a brand name for etanercept, for arthritis"),
    _brand("Remicade", "a brand name for infliximab, for arthritis and bowel disease"),
    _brand("Stelara", "a brand name for ustekinumab, for psoriasis and bowel disease"),
    _brand("Skyrizi", "a brand name for risankizumab, for psoriasis and bowel disease"),
    _brand("Rinvoq", "a brand name for upadacitinib, for arthritis and eczema"),
    _brand("Dupixent", "a brand name for dupilumab, for eczema and asthma"),
    _brand("Cosentyx", "a brand name for secukinumab, for psoriasis"),
    _brand("Ocrevus", "a brand name for ocrelizumab, for multiple sclerosis"),
    _brand(
        "Trikafta", "a brand name for elexacaftor, tezacaftor and ivacaftor, for cystic fibrosis"
    ),
    # Oncology
    _brand("Keytruda", "a brand name for pembrolizumab, a cancer immunotherapy"),
    _brand("Opdivo", "a brand name for nivolumab, a cancer immunotherapy"),
    _brand("Herceptin", "a brand name for trastuzumab, a breast cancer drug"),
    _brand("Avastin", "a brand name for bevacizumab, a cancer drug"),
    _brand("Rituxan", "a brand name for rituximab, for lymphoma and arthritis"),
    _brand("Revlimid", "a brand name for lenalidomide, for multiple myeloma"),
    _brand("Darzalex", "a brand name for daratumumab, for multiple myeloma"),
    _brand("Imbruvica", "a brand name for ibrutinib, for leukemia and lymphoma"),
    _brand("Gleevec", "a brand name for imatinib, for leukemia"),
    _brand("Tagrisso", "a brand name for osimertinib, for lung cancer"),
    _brand("Ibrance", "a brand name for palbociclib, for breast cancer"),
    _brand("Xtandi", "a brand name for enzalutamide, for prostate cancer"),
    # Other
    _brand("Viagra", "a brand name for sildenafil, for erectile dysfunction"),
    _brand("Cialis", "a brand name for tadalafil, for erectile dysfunction"),
    _brand("Flomax", "a brand name for tamsulosin, for an enlarged prostate"),
    _brand("Proscar", "a brand name for finasteride, for an enlarged prostate"),
    _brand("Depo-Provera", "a brand name for injected medroxyprogesterone, a contraceptive"),
    _brand("Eylea", "a brand name for aflibercept, an eye injection for macular degeneration"),
    _brand("Prolia", "a brand name for denosumab, for osteoporosis"),
    _brand("Botox", "a brand name for botulinum toxin, injected to relax muscles"),
)

WORDS: Sequence[str] = (*WHO_ESSENTIAL, *US_PRESCRIBED, *TOP_REVENUE)


if __name__ == "__main__":
    raise SystemExit(run_mixed_import(WORDS, BRANDS, DIFFICULTY_LEVEL, __doc__ or "", tags=TAGS))
