"""Language-specific tools for text processing.

Available language modules:
- langtools.en: English (noun plurals, verb conjugations, adjective comparison)
- langtools.es: Spanish (noun forms, verb conjugations, adjective agreement, etc.)
- langtools.lt: Lithuanian (noun declensions, verb conjugations, etc.)
- langtools.de: German (noun declensions, verb conjugations, etc.)
- langtools.fr: French (noun forms, verb conjugations, adjective agreement, etc.)
- langtools.it: Italian (noun forms, verb conjugations, adjective agreement)
- langtools.nl: Dutch (noun forms, verb conjugations, adjective agreement)
- langtools.sv: Swedish (noun forms, verb conjugations)
- langtools.pt: Portuguese (noun forms, verb conjugations)
- langtools.ro: Romanian (noun forms, verb conjugations, adjective agreement)
- langtools.pl: Polish (noun declensions, verb conjugations, adjective agreement)
- langtools.bg: Bulgarian (noun forms, verb conjugations)
- langtools.hr: Croatian (noun forms, verb conjugations)
- langtools.cs: Czech (noun forms, verb conjugations)
- langtools.da: Danish (noun forms, verb conjugations)
- langtools.et: Estonian (noun forms, verb conjugations)
- langtools.fi: Finnish (noun forms, verb conjugations)
- langtools.el: Greek (noun forms, verb conjugations)
- langtools.hu: Hungarian (noun forms, verb conjugations)
- langtools.ga: Irish (noun forms, verb conjugations)
- langtools.lv: Latvian (noun forms, verb conjugations)
- langtools.mt: Maltese (noun forms, verb conjugations)
- langtools.sk: Slovak (noun forms, verb conjugations)
- langtools.sl: Slovenian (noun forms, verb conjugations)
- langtools.ta: Tamil (noun forms, verb conjugations)
- langtools.te: Telugu (noun forms, verb conjugations)
- langtools.kn: Kannada (noun forms, verb conjugations)
- langtools.ml: Malayalam (noun forms, verb conjugations)
- langtools.si: Sinhala (noun forms, verb conjugations)
- langtools.ja: Japanese (romaji)
- langtools.zh: Chinese (pinyin, character conversion)
"""
